/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FaucetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN"
      | "ETH_AMOUNT"
      | "USDC_AMOUNT"
      | "drip"
      | "dripTo"
      | "ethBalance"
      | "lastFaucetTime"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Drip"): EventFragment;

  encodeFunctionData(functionFragment: "COOLDOWN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ETH_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USDC_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "drip", values?: undefined): string;
  encodeFunctionData(functionFragment: "dripTo", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "ethBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFaucetTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "COOLDOWN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ETH_AMOUNT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "USDC_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "drip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dripTo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ethBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastFaucetTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace DripEvent {
  export type InputTuple = [
    recipient: AddressLike,
    usdcAmount: BigNumberish,
    ethAmount: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    usdcAmount: bigint,
    ethAmount: bigint
  ];
  export interface OutputObject {
    recipient: string;
    usdcAmount: bigint;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Faucet extends BaseContract {
  connect(runner?: ContractRunner | null): Faucet;
  waitForDeployment(): Promise<this>;

  interface: FaucetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  ETH_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  USDC_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  drip: TypedContractMethod<[], [void], "nonpayable">;

  dripTo: TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  ethBalance: TypedContractMethod<[], [bigint], "view">;

  lastFaucetTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "drip"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dripTo"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ethBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastFaucetTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Drip"
  ): TypedContractEvent<
    DripEvent.InputTuple,
    DripEvent.OutputTuple,
    DripEvent.OutputObject
  >;

  filters: {
    "Drip(address,uint256,uint256)": TypedContractEvent<
      DripEvent.InputTuple,
      DripEvent.OutputTuple,
      DripEvent.OutputObject
    >;
    Drip: TypedContractEvent<
      DripEvent.InputTuple,
      DripEvent.OutputTuple,
      DripEvent.OutputObject
    >;
  };
}
