/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as armadaYieldAdapterSol from "./ArmadaYieldAdapter.sol";
export type { armadaYieldAdapterSol };
import type * as armadaYieldVaultSol from "./ArmadaYieldVault.sol";
export type { armadaYieldVaultSol };
export type { ArmadaTreasury } from "./ArmadaTreasury";
