// ABOUTME: Guards that live-network deployment manifests are tracked in git and survive
// ABOUTME: `npm run clean`, while local Anvil manifests stay disposable.
import { expect } from "chai";
import { execFileSync, execSync } from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const REPO_ROOT = path.join(__dirname, "..");

/** True if git's ignore rules match `relPath`, whether or not the file exists or is tracked. */
function isGitIgnored(relPath: string): boolean {
  try {
    execFileSync("git", ["check-ignore", "-q", "--no-index", relPath], { cwd: REPO_ROOT });
    return true;
  } catch {
    return false;
  }
}

describe("Deployment manifest tracking", function () {
  // WHY: mainnet manifests carry the RevenueLock constructor args, deploy blocks and
  // addresses that verification and interrupted-launch recovery depend on; a single
  // untracked copy on the launch machine is too easy to lose (#540).
  it("does not gitignore mainnet manifests", function () {
    for (const f of ["governance-hub-mainnet.json", "crowdfund-hub-mainnet.json", "hub-mainnet-v3.json"]) {
      expect(isGitIgnored(`deployments/${f}`), f).to.equal(false);
    }
  });

  // WHY: local Anvil manifests are regenerated by every `npm run setup` and must not be committed.
  it("still gitignores local manifests", function () {
    for (const f of ["governance-hub.json", "crowdfund-hub.json", "hub-v3.json"]) {
      expect(isGitIgnored(`deployments/${f}`), f).to.equal(true);
    }
  });

  // WHY: `npm run clean` is routine local hygiene; it must never delete a live-network
  // manifest, which would also defeat the mainnet re-run guard (#537).
  it("npm run clean keeps mainnet and Sepolia manifests and removes local ones", function () {
    const clean = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, "package.json"), "utf8")).scripts.clean;
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "manifest-clean-"));
    try {
      fs.mkdirSync(path.join(dir, "deployments"));
      const files = ["governance-hub.json", "governance-hub-sepolia.json", "governance-hub-mainnet.json"];
      for (const f of files) fs.writeFileSync(path.join(dir, "deployments", f), "{}");
      execSync(clean, { cwd: dir, shell: "/bin/sh" });
      expect(fs.readdirSync(path.join(dir, "deployments")).sort())
        .to.deep.equal(["governance-hub-mainnet.json", "governance-hub-sepolia.json"]);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
