/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type G1PointStruct = { x: BigNumberish; y: BigNumberish };

export type G1PointStructOutput = [x: bigint, y: bigint] & {
  x: bigint;
  y: bigint;
};

export type G2PointStruct = {
  x: [BigNumberish, BigNumberish];
  y: [BigNumberish, BigNumberish];
};

export type G2PointStructOutput = [x: [bigint, bigint], y: [bigint, bigint]] & {
  x: [bigint, bigint];
  y: [bigint, bigint];
};

export type SnarkProofStruct = {
  a: G1PointStruct;
  b: G2PointStruct;
  c: G1PointStruct;
};

export type SnarkProofStructOutput = [
  a: G1PointStructOutput,
  b: G2PointStructOutput,
  c: G1PointStructOutput
] & { a: G1PointStructOutput; b: G2PointStructOutput; c: G1PointStructOutput };

export type CommitmentCiphertextStruct = {
  ciphertext: [BytesLike, BytesLike, BytesLike, BytesLike];
  blindedSenderViewingKey: BytesLike;
  blindedReceiverViewingKey: BytesLike;
  annotationData: BytesLike;
  memo: BytesLike;
};

export type CommitmentCiphertextStructOutput = [
  ciphertext: [string, string, string, string],
  blindedSenderViewingKey: string,
  blindedReceiverViewingKey: string,
  annotationData: string,
  memo: string
] & {
  ciphertext: [string, string, string, string];
  blindedSenderViewingKey: string;
  blindedReceiverViewingKey: string;
  annotationData: string;
  memo: string;
};

export type BoundParamsStruct = {
  treeNumber: BigNumberish;
  minGasPrice: BigNumberish;
  unshield: BigNumberish;
  chainID: BigNumberish;
  adaptContract: AddressLike;
  adaptParams: BytesLike;
  commitmentCiphertext: CommitmentCiphertextStruct[];
};

export type BoundParamsStructOutput = [
  treeNumber: bigint,
  minGasPrice: bigint,
  unshield: bigint,
  chainID: bigint,
  adaptContract: string,
  adaptParams: string,
  commitmentCiphertext: CommitmentCiphertextStructOutput[]
] & {
  treeNumber: bigint;
  minGasPrice: bigint;
  unshield: bigint;
  chainID: bigint;
  adaptContract: string;
  adaptParams: string;
  commitmentCiphertext: CommitmentCiphertextStructOutput[];
};

export type TokenDataStruct = {
  tokenType: BigNumberish;
  tokenAddress: AddressLike;
  tokenSubID: BigNumberish;
};

export type TokenDataStructOutput = [
  tokenType: bigint,
  tokenAddress: string,
  tokenSubID: bigint
] & { tokenType: bigint; tokenAddress: string; tokenSubID: bigint };

export type CommitmentPreimageStruct = {
  npk: BytesLike;
  token: TokenDataStruct;
  value: BigNumberish;
};

export type CommitmentPreimageStructOutput = [
  npk: string,
  token: TokenDataStructOutput,
  value: bigint
] & { npk: string; token: TokenDataStructOutput; value: bigint };

export type TransactionStruct = {
  proof: SnarkProofStruct;
  merkleRoot: BytesLike;
  nullifiers: BytesLike[];
  commitments: BytesLike[];
  boundParams: BoundParamsStruct;
  unshieldPreimage: CommitmentPreimageStruct;
};

export type TransactionStructOutput = [
  proof: SnarkProofStructOutput,
  merkleRoot: string,
  nullifiers: string[],
  commitments: string[],
  boundParams: BoundParamsStructOutput,
  unshieldPreimage: CommitmentPreimageStructOutput
] & {
  proof: SnarkProofStructOutput;
  merkleRoot: string;
  nullifiers: string[];
  commitments: string[];
  boundParams: BoundParamsStructOutput;
  unshieldPreimage: CommitmentPreimageStructOutput;
};

export type VerifyingKeyStruct = {
  artifactsIPFSHash: string;
  alpha1: G1PointStruct;
  beta2: G2PointStruct;
  gamma2: G2PointStruct;
  delta2: G2PointStruct;
  ic: G1PointStruct[];
};

export type VerifyingKeyStructOutput = [
  artifactsIPFSHash: string,
  alpha1: G1PointStructOutput,
  beta2: G2PointStructOutput,
  gamma2: G2PointStructOutput,
  delta2: G2PointStructOutput,
  ic: G1PointStructOutput[]
] & {
  artifactsIPFSHash: string;
  alpha1: G1PointStructOutput;
  beta2: G2PointStructOutput;
  gamma2: G2PointStructOutput;
  delta2: G2PointStructOutput;
  ic: G1PointStructOutput[];
};

export type ShieldCiphertextStruct = {
  encryptedBundle: [BytesLike, BytesLike, BytesLike];
  shieldKey: BytesLike;
};

export type ShieldCiphertextStructOutput = [
  encryptedBundle: [string, string, string],
  shieldKey: string
] & { encryptedBundle: [string, string, string]; shieldKey: string };

export type ShieldRequestStruct = {
  preimage: CommitmentPreimageStruct;
  ciphertext: ShieldCiphertextStruct;
};

export type ShieldRequestStructOutput = [
  preimage: CommitmentPreimageStructOutput,
  ciphertext: ShieldCiphertextStructOutput
] & {
  preimage: CommitmentPreimageStructOutput;
  ciphertext: ShieldCiphertextStructOutput;
};

export interface PrivacyPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ZERO_VALUE"
      | "atomicCrossChainUnshield"
      | "getInsertionTreeNumberAndStartingIndex"
      | "getVerificationKey"
      | "handleReceiveFinalizedMessage"
      | "handleReceiveUnfinalizedMessage"
      | "initialize"
      | "initialized"
      | "insertLeaves"
      | "lastEventBlock"
      | "localDomain"
      | "merkleModule"
      | "merkleRoot"
      | "messageTransmitter"
      | "nextLeafIndex"
      | "nftFee"
      | "nullifiers"
      | "owner"
      | "remotePools"
      | "rootHistory"
      | "setRemotePool"
      | "setTestingMode"
      | "setVerificationKey"
      | "shield"
      | "shieldFee"
      | "shieldModule"
      | "snarkSafetyVector"
      | "testingMode"
      | "tokenBlocklist"
      | "tokenIDMapping"
      | "tokenMessenger"
      | "transact"
      | "transactModule"
      | "treasury"
      | "treeNumber"
      | "unshieldFee"
      | "usdc"
      | "verifierModule"
      | "verify"
      | "zeros"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RemotePoolSet" | "TestingModeSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ZERO_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "atomicCrossChainUnshield",
    values: [TransactionStruct, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInsertionTreeNumberAndStartingIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationKey",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveFinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveUnfinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "insertLeaves",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "lastEventBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextLeafIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nftFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nullifiers",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remotePools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rootHistory",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRemotePool",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestingMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationKey",
    values: [BigNumberish, BigNumberish, VerifyingKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "shield",
    values: [ShieldRequestStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "shieldFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "shieldModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "snarkSafetyVector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testingMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBlocklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIDMapping",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transact",
    values: [TransactionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transactModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treeNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unshieldFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [TransactionStruct]
  ): string;
  encodeFunctionData(functionFragment: "zeros", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "ZERO_VALUE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "atomicCrossChainUnshield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInsertionTreeNumberAndStartingIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveFinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveUnfinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertLeaves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEventBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextLeafIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nullifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remotePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRemotePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestingMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shieldFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shieldModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "snarkSafetyVector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testingMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBlocklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIDMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treeNumber", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unshieldFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zeros", data: BytesLike): Result;
}

export namespace RemotePoolSetEvent {
  export type InputTuple = [domain: BigNumberish, poolAddress: BytesLike];
  export type OutputTuple = [domain: bigint, poolAddress: string];
  export interface OutputObject {
    domain: bigint;
    poolAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TestingModeSetEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyPool extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyPool;
  waitForDeployment(): Promise<this>;

  interface: PrivacyPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ZERO_VALUE: TypedContractMethod<[], [string], "view">;

  atomicCrossChainUnshield: TypedContractMethod<
    [
      _transaction: TransactionStruct,
      destinationDomain: BigNumberish,
      finalRecipient: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getInsertionTreeNumberAndStartingIndex: TypedContractMethod<
    [_newCommitments: BigNumberish],
    [[bigint, bigint] & { treeNum: bigint; startIndex: bigint }],
    "view"
  >;

  getVerificationKey: TypedContractMethod<
    [_nullifiers: BigNumberish, _commitments: BigNumberish],
    [VerifyingKeyStructOutput],
    "view"
  >;

  handleReceiveFinalizedMessage: TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  handleReceiveUnfinalizedMessage: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish, arg3: BytesLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _shieldModule: AddressLike,
      _transactModule: AddressLike,
      _merkleModule: AddressLike,
      _verifierModule: AddressLike,
      _tokenMessenger: AddressLike,
      _messageTransmitter: AddressLike,
      _usdc: AddressLike,
      _localDomain: BigNumberish,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  insertLeaves: TypedContractMethod<
    [_leafHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  lastEventBlock: TypedContractMethod<[], [bigint], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  merkleModule: TypedContractMethod<[], [string], "view">;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  messageTransmitter: TypedContractMethod<[], [string], "view">;

  nextLeafIndex: TypedContractMethod<[], [bigint], "view">;

  nftFee: TypedContractMethod<[], [bigint], "view">;

  nullifiers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  remotePools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  rootHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  setRemotePool: TypedContractMethod<
    [domain: BigNumberish, poolAddress: BytesLike],
    [void],
    "nonpayable"
  >;

  setTestingMode: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setVerificationKey: TypedContractMethod<
    [
      _nullifiers: BigNumberish,
      _commitments: BigNumberish,
      _key: VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  shield: TypedContractMethod<
    [_shieldRequests: ShieldRequestStruct[]],
    [void],
    "nonpayable"
  >;

  shieldFee: TypedContractMethod<[], [bigint], "view">;

  shieldModule: TypedContractMethod<[], [string], "view">;

  snarkSafetyVector: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  testingMode: TypedContractMethod<[], [boolean], "view">;

  tokenBlocklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenIDMapping: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        tokenType: bigint;
        tokenAddress: string;
        tokenSubID: bigint;
      }
    ],
    "view"
  >;

  tokenMessenger: TypedContractMethod<[], [string], "view">;

  transact: TypedContractMethod<
    [_transactions: TransactionStruct[]],
    [void],
    "nonpayable"
  >;

  transactModule: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  treeNumber: TypedContractMethod<[], [bigint], "view">;

  unshieldFee: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  verifierModule: TypedContractMethod<[], [string], "view">;

  verify: TypedContractMethod<
    [_transaction: TransactionStruct],
    [boolean],
    "view"
  >;

  zeros: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ZERO_VALUE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "atomicCrossChainUnshield"
  ): TypedContractMethod<
    [
      _transaction: TransactionStruct,
      destinationDomain: BigNumberish,
      finalRecipient: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getInsertionTreeNumberAndStartingIndex"
  ): TypedContractMethod<
    [_newCommitments: BigNumberish],
    [[bigint, bigint] & { treeNum: bigint; startIndex: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerificationKey"
  ): TypedContractMethod<
    [_nullifiers: BigNumberish, _commitments: BigNumberish],
    [VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "handleReceiveFinalizedMessage"
  ): TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReceiveUnfinalizedMessage"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish, arg3: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _shieldModule: AddressLike,
      _transactModule: AddressLike,
      _merkleModule: AddressLike,
      _verifierModule: AddressLike,
      _tokenMessenger: AddressLike,
      _messageTransmitter: AddressLike,
      _usdc: AddressLike,
      _localDomain: BigNumberish,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "insertLeaves"
  ): TypedContractMethod<[_leafHashes: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lastEventBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "merkleModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageTransmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextLeafIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifiers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remotePools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rootHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "setRemotePool"
  ): TypedContractMethod<
    [domain: BigNumberish, poolAddress: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTestingMode"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationKey"
  ): TypedContractMethod<
    [
      _nullifiers: BigNumberish,
      _commitments: BigNumberish,
      _key: VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shield"
  ): TypedContractMethod<
    [_shieldRequests: ShieldRequestStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shieldFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "shieldModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "snarkSafetyVector"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "testingMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenBlocklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenIDMapping"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        tokenType: bigint;
        tokenAddress: string;
        tokenSubID: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transact"
  ): TypedContractMethod<
    [_transactions: TransactionStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treeNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unshieldFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[_transaction: TransactionStruct], [boolean], "view">;
  getFunction(
    nameOrSignature: "zeros"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "RemotePoolSet"
  ): TypedContractEvent<
    RemotePoolSetEvent.InputTuple,
    RemotePoolSetEvent.OutputTuple,
    RemotePoolSetEvent.OutputObject
  >;
  getEvent(
    key: "TestingModeSet"
  ): TypedContractEvent<
    TestingModeSetEvent.InputTuple,
    TestingModeSetEvent.OutputTuple,
    TestingModeSetEvent.OutputObject
  >;

  filters: {
    "RemotePoolSet(uint32,bytes32)": TypedContractEvent<
      RemotePoolSetEvent.InputTuple,
      RemotePoolSetEvent.OutputTuple,
      RemotePoolSetEvent.OutputObject
    >;
    RemotePoolSet: TypedContractEvent<
      RemotePoolSetEvent.InputTuple,
      RemotePoolSetEvent.OutputTuple,
      RemotePoolSetEvent.OutputObject
    >;

    "TestingModeSet(bool)": TypedContractEvent<
      TestingModeSetEvent.InputTuple,
      TestingModeSetEvent.OutputTuple,
      TestingModeSetEvent.OutputObject
    >;
    TestingModeSet: TypedContractEvent<
      TestingModeSetEvent.InputTuple,
      TestingModeSetEvent.OutputTuple,
      TestingModeSetEvent.OutputObject
    >;
  };
}
