/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PrivacyPoolClientInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "crossChainShield"
      | "handleReceiveFinalizedMessage"
      | "handleReceiveUnfinalizedMessage"
      | "hubDomain"
      | "hubPool"
      | "initialize"
      | "initialized"
      | "localDomain"
      | "messageTransmitter"
      | "owner"
      | "setHubPool"
      | "tokenMessenger"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CrossChainShieldInitiated"
      | "HubPoolSet"
      | "UnshieldReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "crossChainShield",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      [BytesLike, BytesLike, BytesLike],
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveFinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveUnfinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "hubDomain", values?: undefined): string;
  encodeFunctionData(functionFragment: "hubPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setHubPool",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "crossChainShield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveFinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveUnfinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hubDomain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hubPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHubPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace CrossChainShieldInitiatedEvent {
  export type InputTuple = [
    sender: AddressLike,
    amount: BigNumberish,
    npk: BytesLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    amount: bigint,
    npk: string,
    nonce: bigint
  ];
  export interface OutputObject {
    sender: string;
    amount: bigint;
    npk: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HubPoolSetEvent {
  export type InputTuple = [hubDomain: BigNumberish, hubPool: BytesLike];
  export type OutputTuple = [hubDomain: bigint, hubPool: string];
  export interface OutputObject {
    hubDomain: bigint;
    hubPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnshieldReceivedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyPoolClient extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyPoolClient;
  waitForDeployment(): Promise<this>;

  interface: PrivacyPoolClientInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  crossChainShield: TypedContractMethod<
    [
      amount: BigNumberish,
      maxFee: BigNumberish,
      npk: BytesLike,
      encryptedBundle: [BytesLike, BytesLike, BytesLike],
      shieldKey: BytesLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  handleReceiveFinalizedMessage: TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  handleReceiveUnfinalizedMessage: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish, arg3: BytesLike],
    [boolean],
    "view"
  >;

  hubDomain: TypedContractMethod<[], [bigint], "view">;

  hubPool: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      _tokenMessenger: AddressLike,
      _messageTransmitter: AddressLike,
      _usdc: AddressLike,
      _localDomain: BigNumberish,
      _hubDomain: BigNumberish,
      _hubPool: BytesLike,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  messageTransmitter: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  setHubPool: TypedContractMethod<
    [_hubDomain: BigNumberish, _hubPool: BytesLike],
    [void],
    "nonpayable"
  >;

  tokenMessenger: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "crossChainShield"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      maxFee: BigNumberish,
      npk: BytesLike,
      encryptedBundle: [BytesLike, BytesLike, BytesLike],
      shieldKey: BytesLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReceiveFinalizedMessage"
  ): TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReceiveUnfinalizedMessage"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish, arg3: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hubDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hubPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _tokenMessenger: AddressLike,
      _messageTransmitter: AddressLike,
      _usdc: AddressLike,
      _localDomain: BigNumberish,
      _hubDomain: BigNumberish,
      _hubPool: BytesLike,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "messageTransmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setHubPool"
  ): TypedContractMethod<
    [_hubDomain: BigNumberish, _hubPool: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CrossChainShieldInitiated"
  ): TypedContractEvent<
    CrossChainShieldInitiatedEvent.InputTuple,
    CrossChainShieldInitiatedEvent.OutputTuple,
    CrossChainShieldInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "HubPoolSet"
  ): TypedContractEvent<
    HubPoolSetEvent.InputTuple,
    HubPoolSetEvent.OutputTuple,
    HubPoolSetEvent.OutputObject
  >;
  getEvent(
    key: "UnshieldReceived"
  ): TypedContractEvent<
    UnshieldReceivedEvent.InputTuple,
    UnshieldReceivedEvent.OutputTuple,
    UnshieldReceivedEvent.OutputObject
  >;

  filters: {
    "CrossChainShieldInitiated(address,uint256,bytes32,uint64)": TypedContractEvent<
      CrossChainShieldInitiatedEvent.InputTuple,
      CrossChainShieldInitiatedEvent.OutputTuple,
      CrossChainShieldInitiatedEvent.OutputObject
    >;
    CrossChainShieldInitiated: TypedContractEvent<
      CrossChainShieldInitiatedEvent.InputTuple,
      CrossChainShieldInitiatedEvent.OutputTuple,
      CrossChainShieldInitiatedEvent.OutputObject
    >;

    "HubPoolSet(uint32,bytes32)": TypedContractEvent<
      HubPoolSetEvent.InputTuple,
      HubPoolSetEvent.OutputTuple,
      HubPoolSetEvent.OutputObject
    >;
    HubPoolSet: TypedContractEvent<
      HubPoolSetEvent.InputTuple,
      HubPoolSetEvent.OutputTuple,
      HubPoolSetEvent.OutputObject
    >;

    "UnshieldReceived(address,uint256)": TypedContractEvent<
      UnshieldReceivedEvent.InputTuple,
      UnshieldReceivedEvent.OutputTuple,
      UnshieldReceivedEvent.OutputObject
    >;
    UnshieldReceived: TypedContractEvent<
      UnshieldReceivedEvent.InputTuple,
      UnshieldReceivedEvent.OutputTuple,
      UnshieldReceivedEvent.OutputObject
    >;
  };
}
