/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type CommitmentCiphertextStruct = {
  ciphertext: [BytesLike, BytesLike, BytesLike, BytesLike];
  blindedSenderViewingKey: BytesLike;
  blindedReceiverViewingKey: BytesLike;
  annotationData: BytesLike;
  memo: BytesLike;
};

export type CommitmentCiphertextStructOutput = [
  ciphertext: [string, string, string, string],
  blindedSenderViewingKey: string,
  blindedReceiverViewingKey: string,
  annotationData: string,
  memo: string
] & {
  ciphertext: [string, string, string, string];
  blindedSenderViewingKey: string;
  blindedReceiverViewingKey: string;
  annotationData: string;
  memo: string;
};

export type TokenDataStruct = {
  tokenType: BigNumberish;
  tokenAddress: AddressLike;
  tokenSubID: BigNumberish;
};

export type TokenDataStructOutput = [
  tokenType: bigint,
  tokenAddress: string,
  tokenSubID: bigint
] & { tokenType: bigint; tokenAddress: string; tokenSubID: bigint };

export type G1PointStruct = { x: BigNumberish; y: BigNumberish };

export type G1PointStructOutput = [x: bigint, y: bigint] & {
  x: bigint;
  y: bigint;
};

export type G2PointStruct = {
  x: [BigNumberish, BigNumberish];
  y: [BigNumberish, BigNumberish];
};

export type G2PointStructOutput = [x: [bigint, bigint], y: [bigint, bigint]] & {
  x: [bigint, bigint];
  y: [bigint, bigint];
};

export type SnarkProofStruct = {
  a: G1PointStruct;
  b: G2PointStruct;
  c: G1PointStruct;
};

export type SnarkProofStructOutput = [
  a: G1PointStructOutput,
  b: G2PointStructOutput,
  c: G1PointStructOutput
] & { a: G1PointStructOutput; b: G2PointStructOutput; c: G1PointStructOutput };

export type BoundParamsStruct = {
  treeNumber: BigNumberish;
  minGasPrice: BigNumberish;
  unshield: BigNumberish;
  chainID: BigNumberish;
  adaptContract: AddressLike;
  adaptParams: BytesLike;
  commitmentCiphertext: CommitmentCiphertextStruct[];
};

export type BoundParamsStructOutput = [
  treeNumber: bigint,
  minGasPrice: bigint,
  unshield: bigint,
  chainID: bigint,
  adaptContract: string,
  adaptParams: string,
  commitmentCiphertext: CommitmentCiphertextStructOutput[]
] & {
  treeNumber: bigint;
  minGasPrice: bigint;
  unshield: bigint;
  chainID: bigint;
  adaptContract: string;
  adaptParams: string;
  commitmentCiphertext: CommitmentCiphertextStructOutput[];
};

export type CommitmentPreimageStruct = {
  npk: BytesLike;
  token: TokenDataStruct;
  value: BigNumberish;
};

export type CommitmentPreimageStructOutput = [
  npk: string,
  token: TokenDataStructOutput,
  value: bigint
] & { npk: string; token: TokenDataStructOutput; value: bigint };

export type TransactionStruct = {
  proof: SnarkProofStruct;
  merkleRoot: BytesLike;
  nullifiers: BytesLike[];
  commitments: BytesLike[];
  boundParams: BoundParamsStruct;
  unshieldPreimage: CommitmentPreimageStruct;
};

export type TransactionStructOutput = [
  proof: SnarkProofStructOutput,
  merkleRoot: string,
  nullifiers: string[],
  commitments: string[],
  boundParams: BoundParamsStructOutput,
  unshieldPreimage: CommitmentPreimageStructOutput
] & {
  proof: SnarkProofStructOutput;
  merkleRoot: string;
  nullifiers: string[];
  commitments: string[];
  boundParams: BoundParamsStructOutput;
  unshieldPreimage: CommitmentPreimageStructOutput;
};

export interface TransactModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ZERO_VALUE"
      | "atomicCrossChainUnshield"
      | "initialized"
      | "lastEventBlock"
      | "localDomain"
      | "merkleModule"
      | "merkleRoot"
      | "messageTransmitter"
      | "nextLeafIndex"
      | "nftFee"
      | "nullifiers"
      | "owner"
      | "remotePools"
      | "rootHistory"
      | "shieldFee"
      | "shieldModule"
      | "snarkSafetyVector"
      | "testingMode"
      | "tokenBlocklist"
      | "tokenIDMapping"
      | "tokenMessenger"
      | "transact"
      | "transactModule"
      | "treasury"
      | "treeNumber"
      | "unshieldFee"
      | "usdc"
      | "verifierModule"
      | "zeros"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CrossChainUnshieldInitiated"
      | "Nullified"
      | "Transact"
      | "Unshield"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ZERO_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "atomicCrossChainUnshield",
    values: [TransactionStruct, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastEventBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextLeafIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nftFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nullifiers",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remotePools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rootHistory",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "shieldFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "shieldModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "snarkSafetyVector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testingMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBlocklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIDMapping",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transact",
    values: [TransactionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transactModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treeNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unshieldFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "zeros", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "ZERO_VALUE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "atomicCrossChainUnshield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEventBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextLeafIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nullifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remotePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shieldFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shieldModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "snarkSafetyVector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testingMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBlocklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIDMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treeNumber", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unshieldFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zeros", data: BytesLike): Result;
}

export namespace CrossChainUnshieldInitiatedEvent {
  export type InputTuple = [
    destinationDomain: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    destinationDomain: bigint,
    recipient: string,
    amount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    destinationDomain: bigint;
    recipient: string;
    amount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NullifiedEvent {
  export type InputTuple = [treeNumber: BigNumberish, nullifier: BytesLike[]];
  export type OutputTuple = [treeNumber: bigint, nullifier: string[]];
  export interface OutputObject {
    treeNumber: bigint;
    nullifier: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactEvent {
  export type InputTuple = [
    treeNumber: BigNumberish,
    startPosition: BigNumberish,
    hash: BytesLike[],
    ciphertext: CommitmentCiphertextStruct[]
  ];
  export type OutputTuple = [
    treeNumber: bigint,
    startPosition: bigint,
    hash: string[],
    ciphertext: CommitmentCiphertextStructOutput[]
  ];
  export interface OutputObject {
    treeNumber: bigint;
    startPosition: bigint;
    hash: string[];
    ciphertext: CommitmentCiphertextStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnshieldEvent {
  export type InputTuple = [
    to: AddressLike,
    token: TokenDataStruct,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    token: TokenDataStructOutput,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    to: string;
    token: TokenDataStructOutput;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TransactModule extends BaseContract {
  connect(runner?: ContractRunner | null): TransactModule;
  waitForDeployment(): Promise<this>;

  interface: TransactModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ZERO_VALUE: TypedContractMethod<[], [string], "view">;

  atomicCrossChainUnshield: TypedContractMethod<
    [
      _transaction: TransactionStruct,
      destinationDomain: BigNumberish,
      finalRecipient: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  lastEventBlock: TypedContractMethod<[], [bigint], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  merkleModule: TypedContractMethod<[], [string], "view">;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  messageTransmitter: TypedContractMethod<[], [string], "view">;

  nextLeafIndex: TypedContractMethod<[], [bigint], "view">;

  nftFee: TypedContractMethod<[], [bigint], "view">;

  nullifiers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  remotePools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  rootHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  shieldFee: TypedContractMethod<[], [bigint], "view">;

  shieldModule: TypedContractMethod<[], [string], "view">;

  snarkSafetyVector: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  testingMode: TypedContractMethod<[], [boolean], "view">;

  tokenBlocklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenIDMapping: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        tokenType: bigint;
        tokenAddress: string;
        tokenSubID: bigint;
      }
    ],
    "view"
  >;

  tokenMessenger: TypedContractMethod<[], [string], "view">;

  transact: TypedContractMethod<
    [_transactions: TransactionStruct[]],
    [void],
    "nonpayable"
  >;

  transactModule: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  treeNumber: TypedContractMethod<[], [bigint], "view">;

  unshieldFee: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  verifierModule: TypedContractMethod<[], [string], "view">;

  zeros: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ZERO_VALUE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "atomicCrossChainUnshield"
  ): TypedContractMethod<
    [
      _transaction: TransactionStruct,
      destinationDomain: BigNumberish,
      finalRecipient: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastEventBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "merkleModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageTransmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextLeafIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifiers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remotePools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rootHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "shieldFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "shieldModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "snarkSafetyVector"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "testingMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenBlocklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenIDMapping"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        tokenType: bigint;
        tokenAddress: string;
        tokenSubID: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transact"
  ): TypedContractMethod<
    [_transactions: TransactionStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treeNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unshieldFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "zeros"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "CrossChainUnshieldInitiated"
  ): TypedContractEvent<
    CrossChainUnshieldInitiatedEvent.InputTuple,
    CrossChainUnshieldInitiatedEvent.OutputTuple,
    CrossChainUnshieldInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "Nullified"
  ): TypedContractEvent<
    NullifiedEvent.InputTuple,
    NullifiedEvent.OutputTuple,
    NullifiedEvent.OutputObject
  >;
  getEvent(
    key: "Transact"
  ): TypedContractEvent<
    TransactEvent.InputTuple,
    TransactEvent.OutputTuple,
    TransactEvent.OutputObject
  >;
  getEvent(
    key: "Unshield"
  ): TypedContractEvent<
    UnshieldEvent.InputTuple,
    UnshieldEvent.OutputTuple,
    UnshieldEvent.OutputObject
  >;

  filters: {
    "CrossChainUnshieldInitiated(uint32,address,uint256,uint64)": TypedContractEvent<
      CrossChainUnshieldInitiatedEvent.InputTuple,
      CrossChainUnshieldInitiatedEvent.OutputTuple,
      CrossChainUnshieldInitiatedEvent.OutputObject
    >;
    CrossChainUnshieldInitiated: TypedContractEvent<
      CrossChainUnshieldInitiatedEvent.InputTuple,
      CrossChainUnshieldInitiatedEvent.OutputTuple,
      CrossChainUnshieldInitiatedEvent.OutputObject
    >;

    "Nullified(uint16,bytes32[])": TypedContractEvent<
      NullifiedEvent.InputTuple,
      NullifiedEvent.OutputTuple,
      NullifiedEvent.OutputObject
    >;
    Nullified: TypedContractEvent<
      NullifiedEvent.InputTuple,
      NullifiedEvent.OutputTuple,
      NullifiedEvent.OutputObject
    >;

    "Transact(uint256,uint256,bytes32[],tuple[])": TypedContractEvent<
      TransactEvent.InputTuple,
      TransactEvent.OutputTuple,
      TransactEvent.OutputObject
    >;
    Transact: TypedContractEvent<
      TransactEvent.InputTuple,
      TransactEvent.OutputTuple,
      TransactEvent.OutputObject
    >;

    "Unshield(address,tuple,uint256,uint256)": TypedContractEvent<
      UnshieldEvent.InputTuple,
      UnshieldEvent.OutputTuple,
      UnshieldEvent.OutputObject
    >;
    Unshield: TypedContractEvent<
      UnshieldEvent.InputTuple,
      UnshieldEvent.OutputTuple,
      UnshieldEvent.OutputObject
    >;
  };
}
