// ABOUTME: Reads the model's DOM-free script blocks out of crowdfund-model.html and assembles the Google Sheet script.
// ABOUTME: Shared by the tests and the sheet build so both always use the exact code that ships in the HTML.

import * as fs from "fs";
import * as path from "path";

export const MODEL_HTML_PATH = path.resolve(__dirname, "crowdfund-model.html");
export const SHEET_FUNCTIONS_PATH = path.resolve(__dirname, "sheet", "sheet-functions.js");
export const SHEET_SCRIPT_PATH = path.resolve(__dirname, "sheet", "Code.gs");

// The DOM-free blocks: the contract port and the scenario helpers (parsing, CSV, validation).
export const PURE_BLOCK_IDS = ["crowdfund-model-engine", "crowdfund-model-scenario"];

export function readModelHtml(): string {
  return fs.readFileSync(MODEL_HTML_PATH, "utf8");
}

export function extractScriptBlock(html: string, id: string): string {
  const match = html.match(new RegExp(`<script id="${id}">([\\s\\S]*?)</script>`));
  if (!match) throw new Error(`script block #${id} not found in ${MODEL_HTML_PATH}`);
  return match[1];
}

/** The engine + scenario blocks, concatenated, exactly as they appear in the HTML. */
export function pureModelSource(): string {
  const html = readModelHtml();
  return PURE_BLOCK_IDS.map((id) => extractScriptBlock(html, id).trim()).join("\n\n");
}

/**
 * Apps Script's save-time syntax check (Esprima-based) predates BigInt literals and rejects
 * `1000000n` with "Unexpected token ILLEGAL", although its V8 runtime supports BigInt. Rewrite
 * each literal as the equivalent `BigInt('1000000')` call; the string form is exact at any size.
 */
export function withoutBigIntLiterals(source: string): string {
  return source.replace(/\b(\d+)n\b/g, "BigInt('$1')");
}

/** The single Apps Script file pasted into the shared sheet: engine + scenario + sheet functions. */
export function buildSheetScript(): string {
  const sheetFunctions = fs.readFileSync(SHEET_FUNCTIONS_PATH, "utf8").replace(/^\/\/ ABOUTME:.*\n/gm, "").trim();
  return [
    "// ABOUTME: GENERATED by `npm run crowdfund-model:build-sheet` from crowdfund-model.html + sheet/sheet-functions.js; do not edit.",
    "// ABOUTME: Paste into the shared Google Sheet's Apps Script editor: exact crowdfund allocation engine + live =ARMADA_* formulas.",
    "",
    withoutBigIntLiterals(pureModelSource()),
    "",
    withoutBigIntLiterals(sheetFunctions),
    "",
  ].join("\n");
}

if (require.main === module) {
  fs.writeFileSync(SHEET_SCRIPT_PATH, buildSheetScript());
  console.log(`Wrote ${path.relative(process.cwd(), SHEET_SCRIPT_PATH)}`);
}
