/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface PausableUpgradableProxyInterface extends Interface {
  getFunction(
    nameOrSignature: "pause" | "transferOwnership" | "unpause" | "upgrade"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProxyOwnershipTransfer"
      | "ProxyPause"
      | "ProxyUnpause"
      | "ProxyUpgrade"
  ): EventFragment;

  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgrade",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
}

export namespace ProxyOwnershipTransferEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProxyPauseEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProxyUnpauseEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProxyUpgradeEvent {
  export type InputTuple = [
    previousImplementation: AddressLike,
    newImplementation: AddressLike
  ];
  export type OutputTuple = [
    previousImplementation: string,
    newImplementation: string
  ];
  export interface OutputObject {
    previousImplementation: string;
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PausableUpgradableProxy extends BaseContract {
  connect(runner?: ContractRunner | null): PausableUpgradableProxy;
  waitForDeployment(): Promise<this>;

  interface: PausableUpgradableProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgrade: TypedContractMethod<
    [_newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgrade"
  ): TypedContractMethod<
    [_newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProxyOwnershipTransfer"
  ): TypedContractEvent<
    ProxyOwnershipTransferEvent.InputTuple,
    ProxyOwnershipTransferEvent.OutputTuple,
    ProxyOwnershipTransferEvent.OutputObject
  >;
  getEvent(
    key: "ProxyPause"
  ): TypedContractEvent<
    ProxyPauseEvent.InputTuple,
    ProxyPauseEvent.OutputTuple,
    ProxyPauseEvent.OutputObject
  >;
  getEvent(
    key: "ProxyUnpause"
  ): TypedContractEvent<
    ProxyUnpauseEvent.InputTuple,
    ProxyUnpauseEvent.OutputTuple,
    ProxyUnpauseEvent.OutputObject
  >;
  getEvent(
    key: "ProxyUpgrade"
  ): TypedContractEvent<
    ProxyUpgradeEvent.InputTuple,
    ProxyUpgradeEvent.OutputTuple,
    ProxyUpgradeEvent.OutputObject
  >;

  filters: {
    "ProxyOwnershipTransfer(address,address)": TypedContractEvent<
      ProxyOwnershipTransferEvent.InputTuple,
      ProxyOwnershipTransferEvent.OutputTuple,
      ProxyOwnershipTransferEvent.OutputObject
    >;
    ProxyOwnershipTransfer: TypedContractEvent<
      ProxyOwnershipTransferEvent.InputTuple,
      ProxyOwnershipTransferEvent.OutputTuple,
      ProxyOwnershipTransferEvent.OutputObject
    >;

    "ProxyPause()": TypedContractEvent<
      ProxyPauseEvent.InputTuple,
      ProxyPauseEvent.OutputTuple,
      ProxyPauseEvent.OutputObject
    >;
    ProxyPause: TypedContractEvent<
      ProxyPauseEvent.InputTuple,
      ProxyPauseEvent.OutputTuple,
      ProxyPauseEvent.OutputObject
    >;

    "ProxyUnpause()": TypedContractEvent<
      ProxyUnpauseEvent.InputTuple,
      ProxyUnpauseEvent.OutputTuple,
      ProxyUnpauseEvent.OutputObject
    >;
    ProxyUnpause: TypedContractEvent<
      ProxyUnpauseEvent.InputTuple,
      ProxyUnpauseEvent.OutputTuple,
      ProxyUnpauseEvent.OutputObject
    >;

    "ProxyUpgrade(address,address)": TypedContractEvent<
      ProxyUpgradeEvent.InputTuple,
      ProxyUpgradeEvent.OutputTuple,
      ProxyUpgradeEvent.OutputObject
    >;
    ProxyUpgrade: TypedContractEvent<
      ProxyUpgradeEvent.InputTuple,
      ProxyUpgradeEvent.OutputTuple,
      ProxyUpgradeEvent.OutputObject
    >;
  };
}
