// ABOUTME: SDK-side helpers for unshield — generateUnshieldProof + populateProvedUnshield with broadcaster-fee (relayer-mediated) support.
// ABOUTME: Dynamic-imports the Railgun SDK + shared-models to dodge jsdom's circomlibjs crash; the populated calldata gets POSTed to /relay by features/unshield/handler.

import { loadHubNetwork } from './network'
import { yieldToPaint } from '@/lib/paint'

type RailgunSdk = typeof import('@railgun-community/wallet')
type SharedModels = typeof import('@railgun-community/shared-models')

async function railgunSdk(): Promise<RailgunSdk> {
  return import('@railgun-community/wallet')
}
async function sharedModels(): Promise<SharedModels> {
  return import('@railgun-community/shared-models')
}

/**
 * Gas details used for proof generation + tx population. The SDK selects the right structural
 * shape based on (network, sendWithPublicWallet) via `getEVMGasTypeForTransaction`:
 *
 *  - Direct user submit (`sendWithPublicWallet=true`) on Hardhat → Type2 (EIP-1559) — accepts
 *    `maxFeePerGas` / `maxPriorityFeePerGas`. Matches what MetaMask sends.
 *  - Broadcaster mode (`sendWithPublicWallet=false`) on Hardhat → Type1 (legacy) — accepts
 *    `gasPrice` instead, because the broadcaster flow requires `overallBatchMinGasPrice` which
 *    the SDK only supports on Type1. Trying to pass Type2 here surfaces the runtime error
 *    `Invalid evmGasType for Hardhat (Broadcaster): expected Type1, received Type2`.
 *
 * Values: 2 000 000 gas / 1 gwei — overkill for Hardhat/Anvil; the relayer's on-chain submit
 * pays actual usage. Sepolia tuning ships separately when we sharpen per-chain gas knobs.
 */
async function buildGasDetails(sendWithPublicWallet: boolean): Promise<unknown> {
  const { EVMGasType } = await sharedModels()
  if (sendWithPublicWallet) {
    return {
      evmGasType: EVMGasType.Type2,
      gasEstimate: 2_000_000n,
      maxFeePerGas: 2_000_000_000n,
      maxPriorityFeePerGas: 1_000_000_000n,
    }
  }
  return {
    evmGasType: EVMGasType.Type1,
    gasEstimate: 2_000_000n,
    gasPrice: 1_000_000_000n,
  }
}

/**
 * One broadcaster output baked into the SNARK proof so the relayer is paid in the same atomic
 * tx as the unshield. Required when `submitRelay` is the submission path — without it, the
 * relayer's server-side fee verifier rejects with `FEE_INSUFFICIENT`. Pass `null` to fall back
 * to a direct user-submitted tx (kept for the A6 wallet-fallback override).
 */
export interface BroadcasterFeeRecipient {
  /** USDC token address on the hub chain. Same address the unshield's first recipient uses. */
  tokenAddress: string
  /** Fee amount in USDC raw units (6 decimals) — must equal the value the relayer published on
   *  `/fees`; the relayer compares against this exact value at request time. */
  amount: bigint
  /** Relayer's `0zk...` address. Sourced from the `FeeSchedule.broadcasterRailgunAddress` field. */
  recipientAddress: string
}

/**
 * Generate the ZK unshield proof for a single recipient. Side-effect on the engine: the proof
 * is cached in memory keyed by the wallet + amounts, and the subsequent `populateProvedUnshield`
 * call must use the SAME inputs or it throws "proof not found".
 *
 * `onProgress` receives a value in [0, 1]; the SDK calls it ~10× over the proof generation
 * window (which is 20-30 seconds on local Anvil, longer on slower machines).
 *
 * `broadcasterFee`: when present, the proof embeds a broadcaster-fee output to the relayer's
 * 0zk address — the relayer-mediated submit path (A3+). When null, the proof is built for direct
 * user submission (legacy path).
 */
export async function generateUnshieldProofForRecipient(opts: {
  walletId: string
  encryptionKey: string
  tokenAddress: string
  recipient: string
  amount: bigint
  broadcasterFee: BroadcasterFeeRecipient | null
  onProgress?: (fraction: number) => void
}): Promise<void> {
  await loadHubNetwork()
  const [{ generateUnshieldProof }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const sendWithPublicWallet = opts.broadcasterFee === null
  // Yield one frame so the caller's "Generating proof…" state paints before the WASM proof gen
  // blocks the main thread for 20-30s.
  await yieldToPaint()
  await generateUnshieldProof(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    opts.encryptionKey,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.recipient,
      },
    ],
    [], // nftAmountRecipients
    opts.broadcasterFee ?? undefined,
    sendWithPublicWallet,
    undefined, // overallBatchMinGasPrice — A6/follow-up: derive from quote for fee staleness check
    (progress) => opts.onProgress?.(progress / 100),
  )
}

/**
 * Populate the transaction object using the proof generated by `generateUnshieldProofForRecipient`.
 * Inputs MUST match the proof call exactly (walletId, recipient, amount, token, broadcasterFee).
 * The SDK's in-memory proof cache is keyed by all of these — a `broadcasterFee` mismatch between
 * the proof and populate steps produces a "proof not found" throw.
 *
 * Returns the raw `to` + `data` + `value`. The handler POSTs `{to, data}` to the relayer's
 * `/relay` endpoint when broadcasterFee is non-null; otherwise it falls back to user-wallet
 * submission via wagmi.
 */
export async function populateUnshieldTransaction(opts: {
  walletId: string
  tokenAddress: string
  recipient: string
  amount: bigint
  broadcasterFee: BroadcasterFeeRecipient | null
}): Promise<{ to: `0x${string}`; data: `0x${string}`; value: bigint }> {
  const [{ populateProvedUnshield }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const sendWithPublicWallet = opts.broadcasterFee === null
  const gasDetails = await buildGasDetails(sendWithPublicWallet)
  const result = await populateProvedUnshield(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.recipient,
      },
    ],
    [], // nftAmountRecipients
    opts.broadcasterFee ?? undefined,
    sendWithPublicWallet,
    undefined, // overallBatchMinGasPrice — see generateUnshieldProofForRecipient
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    gasDetails as any,
  )
  const tx = result.transaction
  if (!tx.to || !tx.data) {
    throw new Error('populateUnshieldTransaction: SDK returned an incomplete transaction')
  }
  return {
    to: tx.to as `0x${string}`,
    data: tx.data as `0x${string}`,
    value: tx.value ? BigInt(tx.value.toString()) : 0n,
  }
}

/**
 * Cross-chain unshield: the proof is generated with the PrivacyPool itself as the unshield
 * recipient (the pool effectively burns the shielded UTXO and emits CCTP messages to deliver
 * USDC to the real recipient on a different chain). Same SDK fn, different recipient.
 *
 * `broadcasterFee`: A5 — when present, embeds a broadcaster-fee output to the relayer's 0zk
 * address so the relayer-mediated hub burn pays the relayer in the same atomic tx. When null,
 * falls back to a direct user-submitted hub burn (kept for the A6 wallet-override fallback).
 */
export async function generateXchainUnshieldProof(opts: {
  walletId: string
  encryptionKey: string
  tokenAddress: string
  privacyPoolAddress: string
  amount: bigint
  broadcasterFee: BroadcasterFeeRecipient | null
  onProgress?: (fraction: number) => void
}): Promise<void> {
  await loadHubNetwork()
  const [{ generateUnshieldProof }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const sendWithPublicWallet = opts.broadcasterFee === null
  // Yield one frame so the caller's "Generating proof…" state paints before the WASM proof gen
  // blocks the main thread for 20-30s.
  await yieldToPaint()
  await generateUnshieldProof(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    opts.encryptionKey,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        // The PrivacyPool itself receives the USDC — it then forwards via CCTP.
        //
        // TODO(#399): the hub now BINDS the destination (recipient, domain, maxFee) into the proof via
        // boundParams.adaptParams (#364/#378, PR #398). This plain generateUnshieldProof sets
        // adaptParams = 0, which the updated atomicCrossChainUnshield REJECTS. Switch this +
        // buildXchainUnshieldTransactionStruct to generateProofTransactions(..., relayAdaptID = {
        // contract: ZeroAddress, parameters: encodeCctpBinding(finalRecipient, destinationDomain,
        // maxFee) }) — the yield.ts pattern. recipientAddress stays the pool (npk = pool; the cross-path
        // replay is closed by a contract-side _transferTokenOut guard). Needs a real-proof e2e — see
        // #399. Coupled: the pool must not be redeployed until this lands, or cross-chain unshields
        // revert. `encodeCctpBinding` is ready in lib/railgun/cctpBinding.ts.
        recipientAddress: opts.privacyPoolAddress,
      },
    ],
    [], // nftAmountRecipients
    opts.broadcasterFee ?? undefined,
    sendWithPublicWallet,
    undefined, // overallBatchMinGasPrice — A6/follow-up
    (progress) => opts.onProgress?.(progress / 100),
  )
}

/**
 * Populate the proof + decode the engine's `transact([tx])` calldata to extract the single
 * inner `Transaction` struct. We need the struct (not the calldata) because the cross-chain
 * entry point is `atomicCrossChainUnshield(tx, ...)` — same struct, different surrounding args.
 *
 * Returns a deeply-cloned mutable object with bigints restored (ethers v6 returns frozen
 * Result proxies and large-magnitude integers are stringified during the JSON deep-clone).
 */
export async function buildXchainUnshieldTransactionStruct(opts: {
  walletId: string
  tokenAddress: string
  privacyPoolAddress: string
  amount: bigint
  broadcasterFee: BroadcasterFeeRecipient | null
}): Promise<unknown> {
  const [{ populateProvedUnshield }, { TXIDVersion, NetworkName }] = await Promise.all([
    railgunSdk(),
    sharedModels(),
  ])
  const { ethers } = await import('ethers')

  // A5: broadcaster mode flips sendWithPublicWallet to false → SDK selects Type1 (legacy) gas
  // because the broadcaster flow needs `overallBatchMinGasPrice`, which only Type1 supports.
  // Type2 here surfaces the SDK's "expected Type1, received Type2" runtime error. Direct submit
  // (broadcasterFee=null) keeps Type2 to match what MetaMask sends.
  const sendWithPublicWallet = opts.broadcasterFee === null
  const gasDetails = await buildGasDetails(sendWithPublicWallet)
  const result = await populateProvedUnshield(
    TXIDVersion.V2_PoseidonMerkle,
    NetworkName.Hardhat,
    opts.walletId,
    [
      {
        tokenAddress: opts.tokenAddress,
        amount: opts.amount,
        recipientAddress: opts.privacyPoolAddress,
      },
    ],
    [], // nftAmountRecipients
    opts.broadcasterFee ?? undefined,
    sendWithPublicWallet,
    undefined, // overallBatchMinGasPrice — A6/follow-up
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    gasDetails as any,
  )
  const calldata = result.transaction.data
  if (!calldata) {
    throw new Error('buildXchainUnshieldTransactionStruct: SDK returned no calldata')
  }

  // The SDK populates `transact([transaction])`; decode and pull the single inner struct.
  const TRANSACT_ABI = [
    'function transact((tuple(tuple(uint256 x, uint256 y) a, tuple(uint256[2] x, uint256[2] y) b, tuple(uint256 x, uint256 y) c) proof, bytes32 merkleRoot, bytes32[] nullifiers, bytes32[] commitments, tuple(uint16 treeNumber, uint72 minGasPrice, uint8 unshield, uint64 chainID, address adaptContract, bytes32 adaptParams, tuple(bytes32[4] ciphertext, bytes32 blindedSenderViewingKey, bytes32 blindedReceiverViewingKey, bytes annotationData, bytes memo)[] commitmentCiphertext) boundParams, tuple(bytes32 npk, tuple(uint8 tokenType, address tokenAddress, uint256 tokenSubID) token, uint120 value) unshieldPreimage)[] _transactions)',
  ]
  const iface = new ethers.Interface(TRANSACT_ABI)
  const decoded = iface.decodeFunctionData('transact', calldata)
  const transactions = decoded[0]
  if (!transactions || transactions.length === 0) {
    throw new Error('buildXchainUnshieldTransactionStruct: no transactions in decoded calldata')
  }

  // ethers v6 returns frozen `Result` proxies. Deep-clone via JSON (with bigint stringification)
  // and restore bigints where the contract expects them. Same trick the legacy app uses.
  const raw = transactions[0]
  const cloned = JSON.parse(
    JSON.stringify(raw, (_, v) => (typeof v === 'bigint' ? v.toString() : v)),
  )
  function restoreBigints(value: unknown): unknown {
    if (value === null || value === undefined) return value
    if (typeof value === 'string' && /^\d+$/.test(value) && value.length > 15) {
      return BigInt(value)
    }
    if (Array.isArray(value)) return value.map(restoreBigints)
    if (typeof value === 'object') {
      const out: Record<string, unknown> = {}
      for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
        out[k] = restoreBigints(v)
      }
      return out
    }
    return value
  }
  return restoreBigints(cloned)
}
