/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMockBurnable,
  IMockBurnableInterface,
} from "../../../../contracts/cctp/MockCCTPV2.sol/IMockBurnable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMockBurnable__factory {
  static readonly abi = _abi;
  static createInterface(): IMockBurnableInterface {
    return new Interface(_abi) as IMockBurnableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMockBurnable {
    return new Contract(address, _abi, runner) as unknown as IMockBurnable;
  }
}
