/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockMessageTransmitterV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "localDomain"
      | "nextMessageNonce"
      | "receiveMessage"
      | "relayer"
      | "sendMessageForBurn"
      | "setRelayer"
      | "setTokenMessenger"
      | "tokenMessenger"
      | "usedNonces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MessageReceived" | "MessageSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextMessageNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveMessage",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendMessageForBurn",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenMessenger",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedNonces",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextMessageNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageForBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedNonces", data: BytesLike): Result;
}

export namespace MessageReceivedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    sourceDomain: BigNumberish,
    sender: BytesLike,
    finalityThresholdExecuted: BigNumberish
  ];
  export type OutputTuple = [
    nonce: bigint,
    sourceDomain: bigint,
    sender: string,
    finalityThresholdExecuted: bigint
  ];
  export interface OutputObject {
    nonce: bigint;
    sourceDomain: bigint;
    sender: string;
    finalityThresholdExecuted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    sourceDomain: BigNumberish,
    destinationDomain: BigNumberish,
    sender: BytesLike,
    recipient: BytesLike,
    destinationCaller: BytesLike,
    minFinalityThreshold: BigNumberish,
    messageBody: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    sourceDomain: bigint,
    destinationDomain: bigint,
    sender: string,
    recipient: string,
    destinationCaller: string,
    minFinalityThreshold: bigint,
    messageBody: string
  ];
  export interface OutputObject {
    nonce: bigint;
    sourceDomain: bigint;
    destinationDomain: bigint;
    sender: string;
    recipient: string;
    destinationCaller: string;
    minFinalityThreshold: bigint;
    messageBody: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockMessageTransmitterV2 extends BaseContract {
  connect(runner?: ContractRunner | null): MockMessageTransmitterV2;
  waitForDeployment(): Promise<this>;

  interface: MockMessageTransmitterV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  nextMessageNonce: TypedContractMethod<[], [bigint], "view">;

  receiveMessage: TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;

  relayer: TypedContractMethod<[], [string], "view">;

  sendMessageForBurn: TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      destinationTokenMessenger: BytesLike,
      destinationCaller: BytesLike,
      burnNonce: BigNumberish,
      burnToken: AddressLike,
      mintRecipient: BytesLike,
      amount: BigNumberish,
      messageSender: BytesLike,
      maxFee: BigNumberish,
      minFinalityThreshold: BigNumberish,
      hookData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenMessenger: TypedContractMethod<
    [_tokenMessenger: AddressLike],
    [void],
    "nonpayable"
  >;

  tokenMessenger: TypedContractMethod<[], [string], "view">;

  usedNonces: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextMessageNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiveMessage"
  ): TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sendMessageForBurn"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      destinationTokenMessenger: BytesLike,
      destinationCaller: BytesLike,
      burnNonce: BigNumberish,
      burnToken: AddressLike,
      mintRecipient: BytesLike,
      amount: BigNumberish,
      messageSender: BytesLike,
      maxFee: BigNumberish,
      minFinalityThreshold: BigNumberish,
      hookData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenMessenger"
  ): TypedContractMethod<[_tokenMessenger: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usedNonces"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "MessageReceived"
  ): TypedContractEvent<
    MessageReceivedEvent.InputTuple,
    MessageReceivedEvent.OutputTuple,
    MessageReceivedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;

  filters: {
    "MessageReceived(uint64,uint32,bytes32,uint32)": TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;
    MessageReceived: TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;

    "MessageSent(uint64,uint32,uint32,bytes32,bytes32,bytes32,uint32,bytes)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
  };
}
