// ABOUTME: GENERATED by `npm run crowdfund-model:build-sheet` from crowdfund-model.html + sheet/sheet-functions.js; do not edit.
// ABOUTME: Paste into the shared Google Sheet's Apps Script editor: exact crowdfund allocation engine + live =ARMADA_* formulas.

// Allocation engine: a line-by-line BigInt port of contracts/crowdfund/ArmadaCrowdfund.sol
// (finalize, _iterateCappedDemand, _computeHopAllocations, _computeAllocation, computeAllocation).
// All USDC values are 6-decimal base units and all math is integer math with Solidity's
// round-down division, so results match the contract to the last unit. This block must stay
// DOM-free: test/crowdfund_model_parity.ts runs it against the real contract.
var CrowdfundModel = (function () {
  'use strict';

  const USDC_UNIT = BigInt('1000000');
  const BPS = BigInt('10000');
  const NUM_HOPS = 3;

  // Mainnet constants from ArmadaCrowdfund.sol. test/crowdfund_model_parity.ts asserts every
  // value against the compiled contract, so a constants change there fails the tests here.
  const CONSTANTS = Object.freeze({
    BASE_SALE: BigInt('1200000') * USDC_UNIT,
    MAX_SALE: BigInt('1800000') * USDC_UNIT,
    MIN_SALE: BigInt('1000000') * USDC_UNIT,
    ELASTIC_TRIGGER: BigInt('1500000') * USDC_UNIT,
    ARM_PRICE: BigInt('1000000'),
    HOP2_BASE_FLOOR_BPS: BigInt('500'),
    HOP2_EXTRA_FLOOR_BPS: BigInt('1000'),
    MIN_COMMIT: BigInt('10') * USDC_UNIT,
    MAX_SEEDS: 180,
    LAUNCH_TEAM_HOP1_BUDGET: 100,
    LAUNCH_TEAM_HOP2_BUDGET: 120,
    MAX_FINALIZE_NODES: 1800,
  });

  // Mirrors the contract's hopConfigs[3] (set in its constructor).
  const HOP_CONFIGS = Object.freeze([
    Object.freeze({ ceilingBps: BigInt('6000'), capUsdc: BigInt('15000') * USDC_UNIT, maxInvites: 3, maxInvitesReceived: 1 }),
    Object.freeze({ ceilingBps: BigInt('4500'), capUsdc: BigInt('4000') * USDC_UNIT, maxInvites: 2, maxInvitesReceived: 10 }),
    Object.freeze({ ceilingBps: BigInt('0'), capUsdc: BigInt('1000') * USDC_UNIT, maxInvites: 0, maxInvitesReceived: 20 }),
  ]);

  // Solidity 0.8 subtraction reverts on underflow; surface the same failure instead of
  // silently producing a negative number.
  function checkedSub(a, b) {
    if (b > a) throw new Error('arithmetic underflow (the contract would revert)');
    return a - b;
  }

  function min(a, b) {
    return a < b ? a : b;
  }

  // _effectiveCap: invitesReceived × per-slot cap for the hop.
  function effectiveCap(hop, invitesReceived) {
    return BigInt(invitesReceived) * HOP_CONFIGS[hop].capUsdc;
  }

  // Expands participants into (participant, hop) nodes, the contract's participantNodes.
  // A participant is { commits: [bigint×3], invitesReceived: [int×3] }; a hop with a zero
  // commit is not a node (on-chain, an invited-but-uncommitted node is skipped by every
  // allocation loop, so it only matters for the rounding buffer; see netProceeds).
  function toNodes(participants) {
    const nodes = [];
    participants.forEach(function (p, index) {
      for (let hop = 0; hop < NUM_HOPS; hop++) {
        if (p.commits[hop] > BigInt('0')) {
          nodes.push({ participant: index, hop: hop, committed: p.commits[hop], invitesReceived: p.invitesReceived[hop] });
        }
      }
    });
    return nodes;
  }

  // _iterateCappedDemand: per-hop and global sums of min(committed, effectiveCap).
  function computeCappedDemand(nodes) {
    let globalCapped = BigInt('0');
    const perHopCapped = [BigInt('0'), BigInt('0'), BigInt('0')];
    for (const node of nodes) {
      if (node.committed === BigInt('0')) continue;
      const capped = min(node.committed, effectiveCap(node.hop, node.invitesReceived));
      perHopCapped[node.hop] += capped;
      globalCapped += capped;
    }
    return { globalCapped: globalCapped, perHopCapped: perHopCapped };
  }

  // _computeHopAllocations. `ceilings` and `demands` are the contract's finalCeilings and
  // finalDemands; `leftovers` are the unused ceilings rolled hop-0 → hop-1 and hop-1 → hop-2.
  function computeHopAllocations(saleSize, perHopCapped) {
    const C = CONSTANTS;
    const hop2Floor = (saleSize * (C.HOP2_BASE_FLOOR_BPS + C.HOP2_EXTRA_FLOOR_BPS)) / BPS;
    const available = checkedSub(saleSize, hop2Floor);
    const basePool = (saleSize * (BPS - C.HOP2_BASE_FLOOR_BPS)) / BPS;

    // Raw BPS terms overlap (60% + 45% of basePool). The extra hop-2 floor is funded solely
    // from hop-0's raw ceiling, preserving hop-1's raw ceiling.
    const hop0Ceiling = checkedSub(
      (basePool * HOP_CONFIGS[0].ceilingBps) / BPS,
      (saleSize * C.HOP2_EXTRA_FLOOR_BPS) / BPS
    );
    const hop1Ceiling = (basePool * HOP_CONFIGS[1].ceilingBps) / BPS;

    // Hop-0: allocate from the available pool.
    const demand0 = perHopCapped[0];
    const alloc0 = demand0 <= hop0Ceiling ? demand0 : hop0Ceiling;
    const leftover0 = checkedSub(hop0Ceiling, alloc0);
    const remainingAvailable = checkedSub(available, alloc0);

    // Hop-1: ceiling boosted by hop-0 leftover, clamped to what is still available.
    const demand1 = perHopCapped[1];
    let hop1EffCeiling = hop1Ceiling + leftover0;
    if (hop1EffCeiling > remainingAvailable) {
      hop1EffCeiling = remainingAvailable;
    }
    const alloc1 = demand1 <= hop1EffCeiling ? demand1 : hop1EffCeiling;
    const leftover1 = checkedSub(hop1EffCeiling, alloc1);

    // Hop-2: floor + hop-1 leftover (no BPS ceiling).
    const demand2 = perHopCapped[2];
    const hop2EffCeiling = hop2Floor + leftover1;
    const alloc2 = demand2 <= hop2EffCeiling ? demand2 : hop2EffCeiling;

    return {
      ceilings: [hop0Ceiling, hop1EffCeiling, hop2EffCeiling],
      demands: [demand0, demand1, demand2],
      allocs: [alloc0, alloc1, alloc2],
      leftovers: [leftover0, leftover1],
      totalAllocUsdc: alloc0 + alloc1 + alloc2,
    };
  }

  // _computeAllocation for one (participant, hop) node against the stored hop ceiling/demand.
  // Refund = raw committed minus allocated (over-cap excess + pro-rata excess).
  function computeNodeAllocation(committed, cap, ceiling, demand) {
    if (committed === BigInt('0')) return { cappedCommitted: BigInt('0'), allocUsdc: BigInt('0'), allocArm: BigInt('0'), refundUsdc: BigInt('0') };
    const cappedCommitted = min(committed, cap);
    const allocUsdc = demand <= ceiling ? cappedCommitted : (cappedCommitted * ceiling) / demand;
    const allocArm = (allocUsdc * BigInt('10') ** BigInt('18')) / CONSTANTS.ARM_PRICE;
    return {
      cappedCommitted: cappedCommitted,
      allocUsdc: allocUsdc,
      allocArm: allocArm,
      refundUsdc: checkedSub(committed, allocUsdc),
    };
  }

  // finalize() pushes allocated USDC to the treasury minus a rounding buffer of one USDC unit
  // per participant node (participantNodes.length, which on-chain also counts invited nodes
  // that never committed).
  function netProceeds(totalAllocUsdc, nodeCount) {
    const roundingBuffer = BigInt(nodeCount);
    return totalAllocUsdc > roundingBuffer ? totalAllocUsdc - roundingBuffer : BigInt('0');
  }

  // Per-participant results, as computeAllocation(addr) would return them after finalize.
  // `hopAllocation` is null in refund mode, where every node refunds its full commitment.
  function participantResults(participants, hopAllocation) {
    return participants.map(function (p) {
      const totals = { committed: BigInt('0'), allocUsdc: BigInt('0'), allocArm: BigInt('0'), refundUsdc: BigInt('0') };
      const hops = [0, 1, 2].map(function (hop) {
        const committed = p.commits[hop];
        if (committed === BigInt('0')) return null;
        const cap = effectiveCap(hop, p.invitesReceived[hop]);
        const alloc = hopAllocation
          ? computeNodeAllocation(committed, cap, hopAllocation.ceilings[hop], hopAllocation.demands[hop])
          : { cappedCommitted: min(committed, cap), allocUsdc: BigInt('0'), allocArm: BigInt('0'), refundUsdc: committed };
        totals.committed += committed;
        totals.allocUsdc += alloc.allocUsdc;
        totals.allocArm += alloc.allocArm;
        totals.refundUsdc += alloc.refundUsdc;
        return {
          committed: committed,
          invitesReceived: p.invitesReceived[hop],
          effectiveCap: cap,
          cappedCommitted: alloc.cappedCommitted,
          allocUsdc: alloc.allocUsdc,
          allocArm: alloc.allocArm,
          refundUsdc: alloc.refundUsdc,
        };
      });
      return Object.assign({ hops: hops }, totals);
    });
  }

  // finalize(): capped-demand minimum check → elastic expansion → hop waterfall →
  // post-allocation minimum check → aggregate results. `refundReason` is null on success,
  // 'capped-demand-below-min' or 'allocation-below-min' for the two refund-mode exits.
  function finalize(participants) {
    const C = CONSTANTS;
    const nodes = toNodes(participants);

    let totalCommitted = BigInt('0');
    const perHopCommitted = [BigInt('0'), BigInt('0'), BigInt('0')];
    const uniqueCommitters = [0, 0, 0];
    for (const node of nodes) {
      totalCommitted += node.committed;
      perHopCommitted[node.hop] += node.committed;
      uniqueCommitters[node.hop]++;
    }

    const demand = computeCappedDemand(nodes);
    const result = {
      totalCommitted: totalCommitted,
      perHopCommitted: perHopCommitted,
      uniqueCommitters: uniqueCommitters,
      cappedDemand: demand.globalCapped,
      perHopCapped: demand.perHopCapped,
      nodeCount: nodes.length,
      saleSize: BigInt('0'),
      refundMode: true,
      refundReason: 'capped-demand-below-min',
      hopAllocation: null,
      totalAllocUsdc: BigInt('0'),
      totalAllocatedArm: BigInt('0'),
      netProceeds: BigInt('0'),
      participants: null,
    };

    if (demand.globalCapped < C.MIN_SALE) {
      result.participants = participantResults(participants, null);
      return result;
    }

    result.saleSize = demand.globalCapped >= C.ELASTIC_TRIGGER ? C.MAX_SALE : C.BASE_SALE;
    result.hopAllocation = computeHopAllocations(result.saleSize, demand.perHopCapped);

    if (result.hopAllocation.totalAllocUsdc < C.MIN_SALE) {
      result.refundReason = 'allocation-below-min';
      result.participants = participantResults(participants, null);
      return result;
    }

    result.refundMode = false;
    result.refundReason = null;
    result.totalAllocUsdc = result.hopAllocation.totalAllocUsdc;
    result.totalAllocatedArm = (result.totalAllocUsdc * BigInt('10') ** BigInt('18')) / C.ARM_PRICE;
    result.netProceeds = netProceeds(result.totalAllocUsdc, nodes.length);
    result.participants = participantResults(participants, result.hopAllocation);
    return result;
  }

  return Object.freeze({
    CONSTANTS: CONSTANTS,
    HOP_CONFIGS: HOP_CONFIGS,
    NUM_HOPS: NUM_HOPS,
    effectiveCap: effectiveCap,
    computeCappedDemand: computeCappedDemand,
    computeHopAllocations: computeHopAllocations,
    computeNodeAllocation: computeNodeAllocation,
    netProceeds: netProceeds,
    finalize: finalize,
  });
})();

// Scenario helpers: turn the editable participant rows (strings, as typed) into engine
// input, validate them against the contract's commit/invite rules, self-fill, format
// amounts, and import/export CSV. DOM-free so the test suite can run it directly.
//
// A row is { name, include, commits: [string×3], invites: [int×3] }; commits are dollar
// strings as typed, invites are invitesReceived per hop (hop-0 is always 1).
var CrowdfundScenario = (function (model) {
  'use strict';

  const C = model.CONSTANTS;
  const HOPS = model.HOP_CONFIGS;
  const USDC_DECIMALS = 6;
  const ARM_DECIMALS = 18;

  const SCENARIO_HEADER = ['name', 'include', 'hop0_commit', 'hop1_commit', 'hop1_invites', 'hop2_commit', 'hop2_invites'];
  const RESULTS_HEADER = [
    'name', 'committed_hop0', 'committed_hop1', 'committed_hop2', 'committed_total',
    'accepted_hop0', 'accepted_hop1', 'accepted_hop2', 'accepted_total', 'arm', 'refund_usdc',
  ];

  function emptyRow() {
    return { name: '', include: true, commits: ['', '', ''], invites: [1, 1, 1] };
  }

  // Exact dollar-string → 6-decimal USDC units. Accepts "$", thousands separators and up to
  // 6 decimals; returns BigInt('0') for blank and null for anything else.
  function parseUsdc(text) {
    const cleaned = String(text).replace(/[\s$,_]/g, '');
    if (cleaned === '') return BigInt('0');
    const match = /^(\d+)(?:\.(\d{0,6}))?$/.exec(cleaned);
    if (!match) return null;
    return BigInt(match[1]) * BigInt('10') ** BigInt(USDC_DECIMALS) + BigInt((match[2] || '').padEnd(USDC_DECIMALS, '0'));
  }

  function groupThousands(digits) {
    return digits.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  }

  // Display formatting rounds down (like the contract), so a shown value never overstates.
  function formatFixed(value, decimals, shown) {
    const scale = BigInt('10') ** BigInt(decimals);
    const whole = groupThousands((value / scale).toString());
    const frac = (value % scale).toString().padStart(decimals, '0').slice(0, shown);
    return shown > 0 ? whole + '.' + frac : whole;
  }

  // Full-precision decimal string with trailing zeros trimmed (no grouping), for CSV.
  function formatExact(value, decimals) {
    const scale = BigInt('10') ** BigInt(decimals);
    const frac = (value % scale).toString().padStart(decimals, '0').replace(/0+$/, '');
    return (value / scale).toString() + (frac ? '.' + frac : '');
  }

  function formatUsdc(units) {
    return '$' + formatFixed(units, USDC_DECIMALS, 2);
  }

  function formatArm(armWei) {
    return formatFixed(armWei, ARM_DECIMALS, 2);
  }

  function formatUsdcExact(units) {
    return formatExact(units, USDC_DECIMALS);
  }

  function formatArmExact(armWei) {
    return formatExact(armWei, ARM_DECIMALS);
  }

  function rowToParticipant(row) {
    const errors = [];
    const commits = row.commits.map(function (text, hop) {
      const value = parseUsdc(text);
      if (value === null) {
        errors.push({ hop: hop, message: '"' + text + '" is not a valid USDC amount' });
        return BigInt('0');
      }
      return value;
    });
    return { participant: { commits: commits, invitesReceived: row.invites.slice() }, errors: errors };
  }

  // Engine input must be whole, non-negative invite counts; anything else is reported by
  // validate() and modeled as 0 invites (cap 0, so the hop's commit is fully refunded).
  function sanitizeInvites(participant) {
    participant.invitesReceived = participant.invitesReceived.map(function (n) {
      return Number.isInteger(n) && n >= 0 ? n : 0;
    });
    return participant;
  }

  // Maximum self-invite fill. Starting at the row's lowest committed hop (hop-0 for a blank
  // row), the participant spends every outgoing invite on themselves: a node's outgoing
  // budget is invitesReceived × maxInvites for its hop. Invites already received from
  // others are kept (counts only ever go up, so the fill is idempotent), and every hop from
  // the entry hop down is filled to its cap. A blank row becomes $15k + $12k + $6k = $33k.
  function selfFill(row) {
    const next = { name: row.name, include: row.include, commits: row.commits.slice(), invites: row.invites.slice() };
    let entry = [0, 1, 2].find(function (hop) {
      return (parseUsdc(row.commits[hop]) || BigInt('0')) > BigInt('0');
    });
    if (entry === undefined) entry = 0;

    if (entry === 0) {
      next.invites[1] = Math.min(HOPS[1].maxInvitesReceived, Math.max(next.invites[1], HOPS[0].maxInvites * next.invites[0]));
    }
    if (entry <= 1) {
      next.invites[2] = Math.min(HOPS[2].maxInvitesReceived, Math.max(next.invites[2], HOPS[1].maxInvites * next.invites[1]));
    }
    for (let hop = entry; hop < model.NUM_HOPS; hop++) {
      next.commits[hop] = formatUsdcExact(model.effectiveCap(hop, next.invites[hop]));
    }
    return next;
  }

  // Issues: { level: 'error' | 'warning' | 'info', row: index | null, hop: 0-2 | null, message }.
  // Errors are inputs the contract would reject; warnings are aggregate invite-supply checks
  // that only see the listed participants; info notes refunds the contract will make.
  function validate(rows) {
    const issues = [];
    let seeds = 0;
    let nodeCount = 0;
    let hop1Supply = C.LAUNCH_TEAM_HOP1_BUDGET;
    let hop2Supply = C.LAUNCH_TEAM_HOP2_BUDGET;
    let hop1Received = 0;
    let hop2Received = 0;

    rows.forEach(function (row, index) {
      if (!row.include) return;
      const converted = rowToParticipant(row);
      converted.errors.forEach(function (e) {
        issues.push({ level: 'error', row: index, hop: e.hop, message: e.message });
      });

      for (let hop = 0; hop < model.NUM_HOPS; hop++) {
        const commit = converted.participant.commits[hop];
        if (commit === BigInt('0')) continue;
        nodeCount++;

        const invites = row.invites[hop];
        const maxReceived = HOPS[hop].maxInvitesReceived;
        if (!Number.isInteger(invites) || invites < 1 || invites > maxReceived) {
          issues.push({
            level: 'error', row: index, hop: hop,
            message: hop === 0
              ? 'Hop-0 (seed) nodes always have exactly 1 invite'
              : 'Invites received must be a whole number from 1 to ' + maxReceived,
          });
          continue;
        }

        const cap = model.effectiveCap(hop, invites);
        if (commit < C.MIN_COMMIT) {
          issues.push({ level: 'error', row: index, hop: hop, message: 'Below the ' + formatUsdc(C.MIN_COMMIT) + ' minimum commit; the contract rejects it' });
        } else if (commit > cap) {
          issues.push({ level: 'info', row: index, hop: hop, message: 'Over the ' + formatUsdc(cap) + ' cap; ' + formatUsdc(commit - cap) + ' is refunded' });
        }

        if (hop === 0) {
          seeds++;
          hop1Supply += HOPS[0].maxInvites * invites;
        } else if (hop === 1) {
          hop1Received += invites;
          hop2Supply += HOPS[1].maxInvites * invites;
        } else {
          hop2Received += invites;
        }
      }
    });

    if (seeds > C.MAX_SEEDS) {
      issues.push({ level: 'error', row: null, hop: 0, message: seeds + ' seeds listed; the contract allows at most ' + C.MAX_SEEDS });
    }
    if (hop1Received > hop1Supply) {
      issues.push({
        level: 'warning', row: null, hop: 1,
        message: 'Listed hop-1 participants hold ' + hop1Received + ' invites, but the listed seeds (' +
          HOPS[0].maxInvites + ' each) and the launch team (' + C.LAUNCH_TEAM_HOP1_BUDGET + ') can issue at most ' + hop1Supply,
      });
    }
    if (hop2Received > hop2Supply) {
      issues.push({
        level: 'warning', row: null, hop: 2,
        message: 'Listed hop-2 participants hold ' + hop2Received + ' invites, but the listed hop-1 nodes (' +
          HOPS[1].maxInvites + ' per invite received) and the launch team (' + C.LAUNCH_TEAM_HOP2_BUDGET + ') can issue at most ' + hop2Supply,
      });
    }
    if (nodeCount > C.MAX_FINALIZE_NODES) {
      issues.push({ level: 'error', row: null, hop: null, message: nodeCount + ' participant nodes; the contract caps nodes at ' + C.MAX_FINALIZE_NODES });
    }
    return issues;
  }

  // Runs the engine over the included rows. `includedRows[k]` is the rows index of
  // result.participants[k].
  function buildModel(rows) {
    const includedRows = [];
    const participants = [];
    rows.forEach(function (row, index) {
      if (!row.include) return;
      includedRows.push(index);
      participants.push(sanitizeInvites(rowToParticipant(row).participant));
    });
    return { includedRows: includedRows, result: model.finalize(participants), issues: validate(rows) };
  }

  function csvField(value) {
    const text = String(value);
    return /[",\r\n]/.test(text) ? '"' + text.replace(/"/g, '""') + '"' : text;
  }

  function csvLine(fields) {
    return fields.map(csvField).join(',');
  }

  // Minimal RFC 4180 reader: quoted fields, doubled quotes, CRLF or LF line endings.
  function parseCsv(text) {
    const records = [];
    let record = [];
    let field = '';
    let quoted = false;
    for (let i = 0; i < text.length; i++) {
      const ch = text[i];
      if (quoted) {
        if (ch === '"' && text[i + 1] === '"') { field += '"'; i++; }
        else if (ch === '"') quoted = false;
        else field += ch;
      } else if (ch === '"') {
        quoted = true;
      } else if (ch === ',') {
        record.push(field); field = '';
      } else if (ch === '\n' || ch === '\r') {
        if (ch === '\r' && text[i + 1] === '\n') i++;
        record.push(field); records.push(record);
        record = []; field = '';
      } else {
        field += ch;
      }
    }
    if (field !== '' || record.length > 0) {
      record.push(field); records.push(record);
    }
    return records.filter(function (r) {
      return r.some(function (f) { return f.trim() !== ''; });
    });
  }

  function scenarioToCsv(rows) {
    const lines = [csvLine(SCENARIO_HEADER)];
    rows.forEach(function (row) {
      lines.push(csvLine([
        row.name, row.include ? 'yes' : 'no',
        row.commits[0], row.commits[1], row.invites[1], row.commits[2], row.invites[2],
      ]));
    });
    return lines.join('\n') + '\n';
  }

  function parseInclude(text) {
    const value = text.trim().toLowerCase();
    if (['', 'yes', 'y', 'true', '1'].indexOf(value) !== -1) return true;
    if (['no', 'n', 'false', '0'].indexOf(value) !== -1) return false;
    return null;
  }

  function parseInvites(text) {
    const value = text.trim();
    if (value === '') return 1;
    return /^\d+$/.test(value) ? Number(value) : null;
  }

  // One record in SCENARIO_HEADER column order (CSV line or sheet row) → { row, errors }.
  // A malformed include/invites field is reported and replaced with that field's default.
  function rowFromFields(fields) {
    const field = function (k) { return fields[k] === undefined ? '' : fields[k]; };
    const errors = [];
    const row = emptyRow();
    row.name = field(0);
    row.commits = [field(2).trim(), field(3).trim(), field(5).trim()];

    const include = parseInclude(field(1));
    if (include === null) errors.push('include must be yes or no');
    else row.include = include;

    [[1, 4], [2, 6]].forEach(function (pair) {
      const invites = parseInvites(field(pair[1]));
      if (invites === null) errors.push('hop' + pair[0] + '_invites must be a whole number');
      else row.invites[pair[0]] = invites;
    });
    return { row: row, errors: errors };
  }

  // Returns { rows, errors }. A malformed header rejects the whole file; a malformed
  // include/invites cell is reported and the row imported with the default for that cell.
  function scenarioFromCsv(text) {
    const records = parseCsv(text);
    const header = (records[0] || []).map(function (h) { return h.trim().toLowerCase(); });
    if (header.join(',') !== SCENARIO_HEADER.join(',')) {
      return { rows: [], errors: ['Expected the header row: ' + SCENARIO_HEADER.join(',')] };
    }
    const rows = [];
    const errors = [];
    records.slice(1).forEach(function (record, i) {
      const parsed = rowFromFields(record);
      parsed.errors.forEach(function (e) { errors.push('Line ' + (i + 2) + ': ' + e); });
      rows.push(parsed.row);
    });
    return { rows: rows, errors: errors };
  }

  // The hop waterfall to display: the contract's own when finalize() computes one;
  // otherwise (capped demand under MIN_SALE) a projection at BASE_SALE so fills are visible.
  function displayedHops(result) {
    return result.hopAllocation || model.computeHopAllocations(C.BASE_SALE, result.perHopCapped);
  }

  // A hop's effective share of the sale size in bps (see the contract's WATERFALL DESIGN NOTE):
  // hop-0 = 60% × 95% − 10% = 47%, hop-1 = 45% × 95% = 42.75%, hop-2 floor = 5% + 10% = 15%.
  function hopShareBps(hop) {
    const bps = BigInt('10000');
    const basePoolBps = bps - C.HOP2_BASE_FLOOR_BPS;
    if (hop === 0) return (HOPS[0].ceilingBps * basePoolBps) / bps - C.HOP2_EXTRA_FLOOR_BPS;
    if (hop === 1) return (HOPS[1].ceilingBps * basePoolBps) / bps;
    return C.HOP2_BASE_FLOOR_BPS + C.HOP2_EXTRA_FLOOR_BPS;
  }

  function resultsToCsv(rows, built) {
    const lines = [csvLine(RESULTS_HEADER)];
    built.includedRows.forEach(function (rowIndex, k) {
      const p = built.result.participants[k];
      const committed = p.hops.map(function (h) { return h ? h.committed : BigInt('0'); });
      const accepted = p.hops.map(function (h) { return h ? h.allocUsdc : BigInt('0'); });
      lines.push(csvLine([rows[rowIndex].name]
        .concat(committed.map(formatUsdcExact), [formatUsdcExact(p.committed)])
        .concat(accepted.map(formatUsdcExact), [formatUsdcExact(p.allocUsdc)])
        .concat([formatArmExact(p.allocArm), formatUsdcExact(p.refundUsdc)])));
    });
    return lines.join('\n') + '\n';
  }

  return Object.freeze({
    SCENARIO_HEADER: SCENARIO_HEADER,
    emptyRow: emptyRow,
    rowFromFields: rowFromFields,
    parseUsdc: parseUsdc,
    formatUsdc: formatUsdc,
    formatArm: formatArm,
    formatUsdcExact: formatUsdcExact,
    formatArmExact: formatArmExact,
    rowToParticipant: rowToParticipant,
    selfFill: selfFill,
    validate: validate,
    buildModel: buildModel,
    scenarioToCsv: scenarioToCsv,
    scenarioFromCsv: scenarioFromCsv,
    resultsToCsv: resultsToCsv,
    displayedHops: displayedHops,
    hopShareBps: hopShareBps,
  });
})(CrowdfundModel);

// ---- Google Sheets layer ----
// Custom functions take the Inputs data rows (columns in SCENARIO_HEADER order: name,
// include, hop0_commit, hop1_commit, hop1_invites, hop2_commit, hop2_invites) and recompute
// whenever any input cell changes. Amounts go in and come out as dollars; all math in
// between is the engine's exact integer math. Dollar outputs are exact to 6 decimals.

var ARMADA_INPUT_COLUMNS = 7;

// A single-cell range arrives as a bare value; every function works on a 2D array.
function armadaRowsOf_(inputs) {
  return Array.isArray(inputs) ? inputs : [[inputs]];
}

// Sheet cell → the text a CSV field would hold, so rowFromFields parses both identically.
function armadaCellText_(value) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'yes' : 'no';
  return String(value);
}

// Name, commits and invites all blank. The include column alone does not make a row, so
// pre-filled dropdowns or checkboxes down the sheet don't create phantom participants.
function armadaIsBlank_(fields) {
  return [0, 2, 3, 4, 5, 6].every(function (k) { return fields[k].trim() === ''; });
}

function armadaUsd_(units) {
  return Number(CrowdfundScenario.formatUsdcExact(units));
}

function armadaArm_(armWei) {
  return Number(CrowdfundScenario.formatArmExact(armWei));
}

// Display ratio for the sheet to format as %; both sides fit exactly in a double.
function armadaRatio_(numerator, denominator) {
  return denominator === BigInt('0') ? '' : Number(numerator) / Number(denominator);
}

// Parses the input rows and runs the engine. `inputIndex[k]` is the input row of rows[k];
// `issues` carry input-row indexes (null for aggregate issues).
function armadaBuild_(inputs) {
  const rows = [];
  const inputIndex = [];
  const fieldIssues = [];
  armadaRowsOf_(inputs).forEach(function (cells, index) {
    const fields = [];
    for (let k = 0; k < ARMADA_INPUT_COLUMNS; k++) fields.push(armadaCellText_(cells[k]));
    if (armadaIsBlank_(fields)) return;
    const parsed = CrowdfundScenario.rowFromFields(fields);
    parsed.errors.forEach(function (message) {
      fieldIssues.push({ level: 'error', row: index, hop: null, message: message });
    });
    inputIndex.push(index);
    rows.push(parsed.row);
  });

  const built = CrowdfundScenario.buildModel(rows);
  const issues = fieldIssues.concat(built.issues.map(function (issue) {
    return Object.assign({}, issue, { row: issue.row === null ? null : inputIndex[issue.row] });
  }));
  const byInput = new Map();
  built.includedRows.forEach(function (rowIndex, k) {
    byInput.set(inputIndex[rowIndex], built.result.participants[k]);
  });
  return { rows: rows, inputIndex: inputIndex, result: built.result, byInput: byInput, issues: issues };
}

function armadaIssueText_(issue) {
  return (issue.hop === null ? '' : 'hop ' + issue.hop + ': ') + issue.message;
}

/**
 * Per-participant allocation, one output row per input row: committed, accepted at hop 0/1/2,
 * ARM, refund (USDC) and that row's issues. Put it in the first column right of the inputs.
 *
 * @param {A2:G} inputs The Inputs data rows (no header).
 * @return Results aligned with the input rows.
 * @customfunction
 */
function ARMADA_RESULTS(inputs) {
  const model = armadaBuild_(inputs);
  const rowIssues = new Map();
  model.issues.forEach(function (issue) {
    if (issue.row === null) return;
    rowIssues.set(issue.row, (rowIssues.has(issue.row) ? rowIssues.get(issue.row) + '; ' : '') + armadaIssueText_(issue));
  });
  const included = new Set(model.inputIndex);

  return armadaRowsOf_(inputs).map(function (cells, index) {
    const issues = rowIssues.get(index) || '';
    const p = model.byInput.get(index);
    if (!p) {
      return ['', '', '', '', '', '', included.has(index) ? (issues || 'excluded') : ''];
    }
    const accepted = p.hops.map(function (h) { return h ? armadaUsd_(h.allocUsdc) : ''; });
    return [armadaUsd_(p.committed)].concat(accepted, [armadaArm_(p.allocArm), armadaUsd_(p.refundUsdc), issues]);
  });
}

/**
 * Sale outcome if the crowdfund finalized with these commits, as label/value rows.
 *
 * @param {Inputs!A2:G} inputs The Inputs data rows (no header).
 * @return Summary rows.
 * @customfunction
 */
function ARMADA_SUMMARY(inputs) {
  const C = CrowdfundModel.CONSTANTS;
  const r = armadaBuild_(inputs).result;
  const fmt = CrowdfundScenario.formatUsdc;
  let outcome = 'Refund mode';
  if (!r.refundMode) outcome = r.saleSize === C.MAX_SALE ? 'Success: expanded sale' : 'Success: base sale';
  let reason = '';
  if (r.refundReason === 'capped-demand-below-min') {
    reason = 'Capped demand is under the ' + fmt(C.MIN_SALE) + ' minimum raise';
  } else if (r.refundReason === 'allocation-below-min') {
    reason = 'Capped demand passes ' + fmt(C.MIN_SALE) + ', but the hop ceilings only allocate ' +
      fmt(r.hopAllocation.totalAllocUsdc) + ' (under the minimum)';
  }
  const maxArm = (C.MAX_SALE * BigInt('10') ** BigInt('18')) / C.ARM_PRICE;
  const refunds = r.participants.reduce(function (sum, p) { return sum + p.refundUsdc; }, BigInt('0'));
  const participants = r.participants.filter(function (p) { return p.committed > BigInt('0'); }).length;
  return [
    ['Outcome', outcome],
    ['Refund reason', reason],
    ['Total committed (USDC)', armadaUsd_(r.totalCommitted)],
    ['Capped demand (USDC)', armadaUsd_(r.cappedDemand)],
    ['Over-cap excess (USDC)', armadaUsd_(r.totalCommitted - r.cappedDemand)],
    ['Sale size (USDC)', r.saleSize === BigInt('0') ? '' : armadaUsd_(r.saleSize)],
    ['ARM allocated', armadaArm_(r.totalAllocatedArm)],
    ['ARM unsold (swept to treasury)', armadaArm_(maxArm - r.totalAllocatedArm)],
    ['USDC refunded', armadaUsd_(refunds)],
    ['Net proceeds to treasury (USDC)', armadaUsd_(r.netProceeds)],
    ['Participants', participants],
    ['Hop nodes', r.nodeCount],
    ['Hop table basis', r.hopAllocation ? 'finalize() waterfall' : 'projected at base sale (finalize() refunds before the waterfall)'],
  ];
}

/**
 * Hop breakdown (as on the crowdfund Details page): share of sale, committers, committed,
 * capped demand, effective ceiling, allocated, fill, accepted rate and rollover per hop.
 *
 * @param {Inputs!A2:G} inputs The Inputs data rows (no header).
 * @return Hop table with a header row and a total row.
 * @customfunction
 */
function ARMADA_HOPS(inputs) {
  const C = CrowdfundModel.CONSTANTS;
  const r = armadaBuild_(inputs).result;
  const hops = CrowdfundScenario.displayedHops(r);
  const names = ['Hop 0 (seeds)', 'Hop 1', 'Hop 2'];
  const table = [['Hop', 'Share of sale', 'Committers', 'Committed', 'Capped demand', 'Effective ceiling', 'Allocated', 'Fill', 'Accepted', 'Rolls over']];
  for (let hop = 0; hop < CrowdfundModel.NUM_HOPS; hop++) {
    table.push([
      names[hop],
      Number(CrowdfundScenario.hopShareBps(hop)) / 10000,
      r.uniqueCommitters[hop],
      armadaUsd_(r.perHopCommitted[hop]),
      armadaUsd_(r.perHopCapped[hop]),
      armadaUsd_(hops.ceilings[hop]),
      armadaUsd_(hops.allocs[hop]),
      armadaRatio_(r.perHopCapped[hop], hops.ceilings[hop]),
      armadaRatio_(hops.allocs[hop], r.perHopCapped[hop]),
      hop < 2 ? armadaUsd_(hops.leftovers[hop]) : '',
    ]);
  }
  const saleSize = r.saleSize === BigInt('0') ? C.BASE_SALE : r.saleSize;
  table.push([
    'Total', 1, r.nodeCount, armadaUsd_(r.totalCommitted), armadaUsd_(r.cappedDemand), armadaUsd_(saleSize),
    armadaUsd_(hops.totalAllocUsdc), armadaRatio_(r.cappedDemand, saleSize), armadaRatio_(hops.totalAllocUsdc, r.cappedDemand), '',
  ]);
  return table;
}

/**
 * Every issue: inputs the contract would reject, over-cap refunds, and invite-supply warnings.
 *
 * @param {Inputs!A2:G} inputs The Inputs data rows (no header).
 * @param {2} firstRow Sheet row number of the first input row (default 2), for "Row N" labels.
 * @return Rows of level, where, message.
 * @customfunction
 */
function ARMADA_ISSUES(inputs, firstRow) {
  const model = armadaBuild_(inputs);
  const rows = armadaRowsOf_(inputs);
  const start = typeof firstRow === 'number' ? firstRow : 2;
  if (model.issues.length === 0) return [['ok', '', 'No issues']];
  return model.issues.map(function (issue) {
    let where = 'All participants';
    if (issue.row !== null) {
      const name = armadaCellText_(rows[issue.row][0]).trim();
      where = 'Row ' + (start + issue.row) + (name ? ' (' + name + ')' : '');
      if (issue.hop !== null) where += ' · hop ' + issue.hop;
    } else if (issue.hop !== null) {
      where += ' · hop ' + issue.hop;
    }
    return [issue.level, where, issue.message];
  });
}

/**
 * Checks the engine against golden vectors (40 self-filled seeds; a non-exact pro-rata).
 * Shows OK when this sheet computes exactly what the contract would.
 *
 * @return OK or FAIL with details.
 * @customfunction
 */
function ARMADA_SELFTEST() {
  try {
    const U = BigInt('1000000');
    const selfFilled = function () { return { commits: [BigInt('15000') * U, BigInt('12000') * U, BigInt('6000') * U], invitesReceived: [1, 3, 6] }; };
    const r = CrowdfundModel.finalize(Array.from({ length: 40 }, selfFilled));
    const proRata = CrowdfundModel.computeNodeAllocation(BigInt('15000') * U, BigInt('15000') * U, BigInt('564000') * U, BigInt('601000') * U);
    const checks = [
      ['sale size', r.saleSize, BigInt('1200000') * U],
      ['total allocated', r.totalAllocUsdc, BigInt('1200000') * U],
      ['participant ARM', r.participants[0].allocArm, BigInt('30000') * U * BigInt('10') ** BigInt('12')],
      ['participant refund', r.participants[0].refundUsdc, BigInt('3000') * U],
      ['pro-rata floor', proRata.allocUsdc, BigInt('14076539101')],
    ];
    const failed = checks.filter(function (c) { return c[1] !== c[2]; });
    if (failed.length > 0) {
      return 'FAIL: ' + failed.map(function (c) { return c[0] + ' = ' + c[1] + ', expected ' + c[2]; }).join('; ');
    }
    return 'OK: engine matches the contract golden vectors';
  } catch (e) {
    return 'FAIL: ' + e;
  }
}

// ---- Setup menu ----

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Armada')
    .addItem('Set up model sheets', 'armadaSetUpSheets')
    .addItem('Run self-test', 'armadaRunSelfTest')
    .addToUi();
}

function armadaRunSelfTest() {
  SpreadsheetApp.getUi().alert(ARMADA_SELFTEST());
}

// Creates (or refreshes) the Inputs and Model tabs: headers, live formulas, formats and the
// include dropdown. Never touches input data rows, so it is safe to rerun.
function armadaSetUpSheets() {
  const spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  const usd = '$#,##0.00####';
  const arm = '#,##0.00####';
  const pct = '0.0%';

  const inputs = spreadsheet.getSheetByName('Inputs') || spreadsheet.insertSheet('Inputs');
  inputs.getRange('A1:G1').setValues([CrowdfundScenario.SCENARIO_HEADER.slice()]).setFontWeight('bold');
  inputs.getRange('I1:O1')
    .setValues([['Committed', 'Accepted hop 0', 'Accepted hop 1', 'Accepted hop 2', 'ARM', 'Refund', 'Issues']])
    .setFontWeight('bold');
  inputs.getRange('I2').setFormula('=ARMADA_RESULTS(A2:G)');
  ['C2:D', 'F2:F', 'I2:L', 'N2:N'].forEach(function (a1) { inputs.getRange(a1).setNumberFormat(usd); });
  inputs.getRange('M2:M').setNumberFormat(arm);
  inputs.getRange('B2:B').setDataValidation(
    SpreadsheetApp.newDataValidation().requireValueInList(['yes', 'no'], true).setAllowInvalid(false).build()
  );
  inputs.setFrozenRows(1);

  const model = spreadsheet.getSheetByName('Model') || spreadsheet.insertSheet('Model');
  model.getRange('A1').setFormula('=ARMADA_SUMMARY(Inputs!A2:G)');
  ['B3:B6', 'B9:B10'].forEach(function (a1) { model.getRange(a1).setNumberFormat(usd); });
  model.getRange('B7:B8').setNumberFormat(arm);
  model.getRange('A16').setValues([['Hop breakdown']]).setFontWeight('bold');
  model.getRange('A17').setFormula('=ARMADA_HOPS(Inputs!A2:G)');
  model.getRange('A17:J17').setFontWeight('bold');
  model.getRange('B18:B21').setNumberFormat('0.00%');
  model.getRange('D18:G21').setNumberFormat(usd);
  model.getRange('H18:I21').setNumberFormat(pct);
  model.getRange('J18:J21').setNumberFormat(usd);
  model.getRange('A23').setValues([['Issues']]).setFontWeight('bold');
  model.getRange('A24').setFormula('=ARMADA_ISSUES(Inputs!A2:G, 2)');
}
