/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as icctpv2Sol from "./ICCTPV2.sol";
export type { icctpv2Sol };
import type * as mockCctpv2Sol from "./MockCCTPV2.sol";
export type { mockCctpv2Sol };
export type { MockUSDCV2 } from "./MockUSDCV2";
