/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMessageTransmitterV2,
  IMessageTransmitterV2Interface,
} from "../../../../contracts/cctp/ICCTPV2.sol/IMessageTransmitterV2";

const _abi = [
  {
    inputs: [],
    name: "localDomain",
    outputs: [
      {
        internalType: "uint32",
        name: "domain",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "attestation",
        type: "bytes",
      },
    ],
    name: "receiveMessage",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMessageTransmitterV2__factory {
  static readonly abi = _abi;
  static createInterface(): IMessageTransmitterV2Interface {
    return new Interface(_abi) as IMessageTransmitterV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMessageTransmitterV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMessageTransmitterV2;
  }
}
