/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface PrivacyPoolStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ZERO_VALUE"
      | "initialized"
      | "lastEventBlock"
      | "localDomain"
      | "merkleModule"
      | "merkleRoot"
      | "messageTransmitter"
      | "nextLeafIndex"
      | "nftFee"
      | "nullifiers"
      | "owner"
      | "remotePools"
      | "rootHistory"
      | "shieldFee"
      | "shieldModule"
      | "snarkSafetyVector"
      | "testingMode"
      | "tokenBlocklist"
      | "tokenIDMapping"
      | "tokenMessenger"
      | "transactModule"
      | "treasury"
      | "treeNumber"
      | "unshieldFee"
      | "usdc"
      | "verifierModule"
      | "zeros"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ZERO_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastEventBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextLeafIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nftFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nullifiers",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remotePools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rootHistory",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "shieldFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "shieldModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "snarkSafetyVector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testingMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBlocklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenIDMapping",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenMessenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transactModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treeNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unshieldFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "zeros", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "ZERO_VALUE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEventBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merkleModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextLeafIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nullifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remotePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shieldFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shieldModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "snarkSafetyVector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testingMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBlocklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenIDMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenMessenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treeNumber", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unshieldFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zeros", data: BytesLike): Result;
}

export interface PrivacyPoolStorage extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyPoolStorage;
  waitForDeployment(): Promise<this>;

  interface: PrivacyPoolStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ZERO_VALUE: TypedContractMethod<[], [string], "view">;

  initialized: TypedContractMethod<[], [boolean], "view">;

  lastEventBlock: TypedContractMethod<[], [bigint], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  merkleModule: TypedContractMethod<[], [string], "view">;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  messageTransmitter: TypedContractMethod<[], [string], "view">;

  nextLeafIndex: TypedContractMethod<[], [bigint], "view">;

  nftFee: TypedContractMethod<[], [bigint], "view">;

  nullifiers: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  remotePools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  rootHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;

  shieldFee: TypedContractMethod<[], [bigint], "view">;

  shieldModule: TypedContractMethod<[], [string], "view">;

  snarkSafetyVector: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  testingMode: TypedContractMethod<[], [boolean], "view">;

  tokenBlocklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenIDMapping: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        tokenType: bigint;
        tokenAddress: string;
        tokenSubID: bigint;
      }
    ],
    "view"
  >;

  tokenMessenger: TypedContractMethod<[], [string], "view">;

  transactModule: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  treeNumber: TypedContractMethod<[], [bigint], "view">;

  unshieldFee: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  verifierModule: TypedContractMethod<[], [string], "view">;

  zeros: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ZERO_VALUE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastEventBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "merkleModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageTransmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextLeafIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifiers"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remotePools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rootHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "shieldFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "shieldModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "snarkSafetyVector"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "testingMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenBlocklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenIDMapping"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint] & {
        tokenType: bigint;
        tokenAddress: string;
        tokenSubID: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenMessenger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transactModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treeNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unshieldFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "zeros"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  filters: {};
}
