/**
 * Railgun Wallet SDK Initialization for Browser
 *
 * Initializes the Railgun engine with browser-compatible storage.
 * See: https://docs.railgun.org/developer-guide/wallet/getting-started
 */

import { startRailgunEngine, setLoggers } from '@railgun-community/wallet'
import { POI } from '@railgun-community/engine'
import { createWebDatabase } from './database'
import { createBrowserArtifactStore, clearArtifactCache } from './artifacts'
import {
  loadTestArtifacts,
  checkTestArtifactsAvailable,
} from './test-artifacts'

// Track initialization state
let isInitialized = false
let initPromise: Promise<void> | null = null
let initError: Error | null = null

/**
 * Initialize Railgun SDK for browser
 *
 * This should be called once when the app starts.
 * Safe to call multiple times - subsequent calls will return immediately.
 */
export async function initRailgun(): Promise<void> {
  if (isInitialized) {
    return
  }

  if (initError) {
    throw initError
  }

  if (initPromise) {
    return initPromise
  }

  initPromise = doInit()

  try {
    await initPromise
    isInitialized = true
  } catch (err) {
    initError = err instanceof Error ? err : new Error(String(err))
    initPromise = null
    throw initError
  }
}

async function doInit(): Promise<void> {
  console.log('[railgun] Initializing Railgun SDK...')

  // Set up logging
  setLoggers(
    (msg: string) => console.log('[railgun]', msg),
    (err: Error) => console.error('[railgun]', err),
  )

  // Create browser-compatible database
  const db = createWebDatabase('railgun-poc-wallet')

  // Create artifact store
  const artifactStore = createBrowserArtifactStore()

  // Initialize engine
  // - walletSource: identifier for this app (max 16 chars, lowercase)
  // - useNativeArtifacts: false for browser (use WASM)
  // - skipMerkletreeScans: false to enable balance scanning
  await startRailgunEngine(
    'railgunpoc', // walletSource (max 16 chars, lowercase, no special chars)
    db, // database
    true, // shouldDebug
    artifactStore, // artifactStore
    false, // useNativeArtifacts (false = WASM for browser)
    false, // skipMerkletreeScans (false = enable balance scanning)
    undefined, // poiNodeURLs (not needed for local devnet)
    undefined, // customPOILists
    true, // verboseScanLogging (helpful for debugging)
  )

  // Initialize POI with a dummy node interface for local devnet.
  // This is required because the SDK calls POI.isRequiredForChain() during proof generation,
  // which in turn calls nodeInterface.isRequired(). Without a nodeInterface, we get:
  // "Cannot read properties of undefined (reading isRequired)"
  try {
    const dummyNodeInterface = {
      isActive: () => false,
      isRequired: async () => false,
      getPOIsPerList: async () => ({}),
      getPOIMerkleProofs: async () => ({}),
      validatePOIMerkleroots: async () => true,
      submitPOI: async () => {},
      submitLegacyTransactProofs: async () => {},
    }
    POI.init([], dummyNodeInterface as unknown as Parameters<typeof POI.init>[1])
    console.log(
      '[railgun] POI disabled with dummy node interface for local devnet',
    )
  } catch (error) {
    console.warn('[railgun] Failed to initialize POI:', error)
  }

  // Load test artifacts for local devnet.
  // These artifacts match the verification keys deployed to the contract.
  // Without this, proofs generated by the SDK won't verify on-chain.
  const hasTestArtifacts = await checkTestArtifactsAvailable()
  if (hasTestArtifacts) {
    // Clear any previously cached IPFS artifacts from IndexedDB
    // to ensure we use our test artifacts instead
    console.log('[railgun] Clearing IndexedDB artifact cache...')
    await clearArtifactCache()

    console.log('[railgun] Loading test artifacts for local devnet...')
    await loadTestArtifacts()
    console.log('[railgun] Test artifacts loaded and injected into SDK cache')
  } else {
    console.warn(
      '[railgun] Test artifacts not found. Run: npm run prepare:artifacts',
    )
  }

  console.log('[railgun] Engine initialized successfully')
}

/**
 * Check if Railgun SDK is initialized
 */
export function isRailgunInitialized(): boolean {
  return isInitialized
}

/**
 * Get initialization error if any
 */
export function getRailgunInitError(): Error | null {
  return initError
}

/**
 * Reset initialization state (for retry)
 */
export function resetRailgunInit(): void {
  isInitialized = false
  initPromise = null
  initError = null
}
