/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUnshieldCallback,
  IUnshieldCallbackInterface,
} from "../../../../contracts/railgun/interfaces/IUnshieldCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint120",
        name: "amount",
        type: "uint120",
      },
      {
        internalType: "address",
        name: "originalSender",
        type: "address",
      },
    ],
    name: "onRailgunUnshield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUnshieldCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IUnshieldCallbackInterface {
    return new Interface(_abi) as IUnshieldCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUnshieldCallback {
    return new Contract(address, _abi, runner) as unknown as IUnshieldCallback;
  }
}
