/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IMerkleModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getInsertionTreeNumberAndStartingIndex"
      | "hashLeftRight"
      | "initializeMerkle"
      | "insertLeaves"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getInsertionTreeNumberAndStartingIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashLeftRight",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeMerkle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "insertLeaves",
    values: [BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getInsertionTreeNumberAndStartingIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashLeftRight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeMerkle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertLeaves",
    data: BytesLike
  ): Result;
}

export interface IMerkleModule extends BaseContract {
  connect(runner?: ContractRunner | null): IMerkleModule;
  waitForDeployment(): Promise<this>;

  interface: IMerkleModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getInsertionTreeNumberAndStartingIndex: TypedContractMethod<
    [_newCommitments: BigNumberish],
    [[bigint, bigint] & { treeNum: bigint; startIndex: bigint }],
    "view"
  >;

  hashLeftRight: TypedContractMethod<
    [_left: BytesLike, _right: BytesLike],
    [string],
    "view"
  >;

  initializeMerkle: TypedContractMethod<[], [void], "nonpayable">;

  insertLeaves: TypedContractMethod<
    [_leafHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getInsertionTreeNumberAndStartingIndex"
  ): TypedContractMethod<
    [_newCommitments: BigNumberish],
    [[bigint, bigint] & { treeNum: bigint; startIndex: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashLeftRight"
  ): TypedContractMethod<
    [_left: BytesLike, _right: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeMerkle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "insertLeaves"
  ): TypedContractMethod<[_leafHashes: BytesLike[]], [void], "nonpayable">;

  filters: {};
}
