/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type G1PointStruct = { x: BigNumberish; y: BigNumberish };

export type G1PointStructOutput = [x: bigint, y: bigint] & {
  x: bigint;
  y: bigint;
};

export type G2PointStruct = {
  x: [BigNumberish, BigNumberish];
  y: [BigNumberish, BigNumberish];
};

export type G2PointStructOutput = [x: [bigint, bigint], y: [bigint, bigint]] & {
  x: [bigint, bigint];
  y: [bigint, bigint];
};

export type SnarkProofStruct = {
  a: G1PointStruct;
  b: G2PointStruct;
  c: G1PointStruct;
};

export type SnarkProofStructOutput = [
  a: G1PointStructOutput,
  b: G2PointStructOutput,
  c: G1PointStructOutput
] & { a: G1PointStructOutput; b: G2PointStructOutput; c: G1PointStructOutput };

export type CommitmentCiphertextStruct = {
  ciphertext: [BytesLike, BytesLike, BytesLike, BytesLike];
  blindedSenderViewingKey: BytesLike;
  blindedReceiverViewingKey: BytesLike;
  annotationData: BytesLike;
  memo: BytesLike;
};

export type CommitmentCiphertextStructOutput = [
  ciphertext: [string, string, string, string],
  blindedSenderViewingKey: string,
  blindedReceiverViewingKey: string,
  annotationData: string,
  memo: string
] & {
  ciphertext: [string, string, string, string];
  blindedSenderViewingKey: string;
  blindedReceiverViewingKey: string;
  annotationData: string;
  memo: string;
};

export type BoundParamsStruct = {
  treeNumber: BigNumberish;
  minGasPrice: BigNumberish;
  unshield: BigNumberish;
  chainID: BigNumberish;
  adaptContract: AddressLike;
  adaptParams: BytesLike;
  commitmentCiphertext: CommitmentCiphertextStruct[];
};

export type BoundParamsStructOutput = [
  treeNumber: bigint,
  minGasPrice: bigint,
  unshield: bigint,
  chainID: bigint,
  adaptContract: string,
  adaptParams: string,
  commitmentCiphertext: CommitmentCiphertextStructOutput[]
] & {
  treeNumber: bigint;
  minGasPrice: bigint;
  unshield: bigint;
  chainID: bigint;
  adaptContract: string;
  adaptParams: string;
  commitmentCiphertext: CommitmentCiphertextStructOutput[];
};

export type TokenDataStruct = {
  tokenType: BigNumberish;
  tokenAddress: AddressLike;
  tokenSubID: BigNumberish;
};

export type TokenDataStructOutput = [
  tokenType: bigint,
  tokenAddress: string,
  tokenSubID: bigint
] & { tokenType: bigint; tokenAddress: string; tokenSubID: bigint };

export type CommitmentPreimageStruct = {
  npk: BytesLike;
  token: TokenDataStruct;
  value: BigNumberish;
};

export type CommitmentPreimageStructOutput = [
  npk: string,
  token: TokenDataStructOutput,
  value: bigint
] & { npk: string; token: TokenDataStructOutput; value: bigint };

export type TransactionStruct = {
  proof: SnarkProofStruct;
  merkleRoot: BytesLike;
  nullifiers: BytesLike[];
  commitments: BytesLike[];
  boundParams: BoundParamsStruct;
  unshieldPreimage: CommitmentPreimageStruct;
};

export type TransactionStructOutput = [
  proof: SnarkProofStructOutput,
  merkleRoot: string,
  nullifiers: string[],
  commitments: string[],
  boundParams: BoundParamsStructOutput,
  unshieldPreimage: CommitmentPreimageStructOutput
] & {
  proof: SnarkProofStructOutput;
  merkleRoot: string;
  nullifiers: string[];
  commitments: string[];
  boundParams: BoundParamsStructOutput;
  unshieldPreimage: CommitmentPreimageStructOutput;
};

export type VerifyingKeyStruct = {
  artifactsIPFSHash: string;
  alpha1: G1PointStruct;
  beta2: G2PointStruct;
  gamma2: G2PointStruct;
  delta2: G2PointStruct;
  ic: G1PointStruct[];
};

export type VerifyingKeyStructOutput = [
  artifactsIPFSHash: string,
  alpha1: G1PointStructOutput,
  beta2: G2PointStructOutput,
  gamma2: G2PointStructOutput,
  delta2: G2PointStructOutput,
  ic: G1PointStructOutput[]
] & {
  artifactsIPFSHash: string;
  alpha1: G1PointStructOutput;
  beta2: G2PointStructOutput;
  gamma2: G2PointStructOutput;
  delta2: G2PointStructOutput;
  ic: G1PointStructOutput[];
};

export type ShieldCiphertextStruct = {
  encryptedBundle: [BytesLike, BytesLike, BytesLike];
  shieldKey: BytesLike;
};

export type ShieldCiphertextStructOutput = [
  encryptedBundle: [string, string, string],
  shieldKey: string
] & { encryptedBundle: [string, string, string]; shieldKey: string };

export type ShieldRequestStruct = {
  preimage: CommitmentPreimageStruct;
  ciphertext: ShieldCiphertextStruct;
};

export type ShieldRequestStructOutput = [
  preimage: CommitmentPreimageStructOutput,
  ciphertext: ShieldCiphertextStructOutput
] & {
  preimage: CommitmentPreimageStructOutput;
  ciphertext: ShieldCiphertextStructOutput;
};

export interface IPrivacyPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "atomicCrossChainUnshield"
      | "handleReceiveFinalizedMessage"
      | "handleReceiveUnfinalizedMessage"
      | "initialize"
      | "setRemotePool"
      | "setTestingMode"
      | "setVerificationKey"
      | "shield"
      | "transact"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RemotePoolSet" | "TestingModeSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "atomicCrossChainUnshield",
    values: [TransactionStruct, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveFinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveUnfinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRemotePool",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestingMode",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationKey",
    values: [BigNumberish, BigNumberish, VerifyingKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "shield",
    values: [ShieldRequestStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transact",
    values: [TransactionStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "atomicCrossChainUnshield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveFinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveUnfinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRemotePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestingMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transact", data: BytesLike): Result;
}

export namespace RemotePoolSetEvent {
  export type InputTuple = [domain: BigNumberish, poolAddress: BytesLike];
  export type OutputTuple = [domain: bigint, poolAddress: string];
  export interface OutputObject {
    domain: bigint;
    poolAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TestingModeSetEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPrivacyPool extends BaseContract {
  connect(runner?: ContractRunner | null): IPrivacyPool;
  waitForDeployment(): Promise<this>;

  interface: IPrivacyPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  atomicCrossChainUnshield: TypedContractMethod<
    [
      _transaction: TransactionStruct,
      destinationDomain: BigNumberish,
      finalRecipient: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  handleReceiveFinalizedMessage: TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  handleReceiveUnfinalizedMessage: TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      _shieldModule: AddressLike,
      _transactModule: AddressLike,
      _merkleModule: AddressLike,
      _verifierModule: AddressLike,
      _tokenMessenger: AddressLike,
      _messageTransmitter: AddressLike,
      _usdc: AddressLike,
      _localDomain: BigNumberish,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setRemotePool: TypedContractMethod<
    [domain: BigNumberish, poolAddress: BytesLike],
    [void],
    "nonpayable"
  >;

  setTestingMode: TypedContractMethod<[enabled: boolean], [void], "nonpayable">;

  setVerificationKey: TypedContractMethod<
    [
      nullifiers: BigNumberish,
      commitments: BigNumberish,
      key: VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  shield: TypedContractMethod<
    [_shieldRequests: ShieldRequestStruct[]],
    [void],
    "nonpayable"
  >;

  transact: TypedContractMethod<
    [_transactions: TransactionStruct[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "atomicCrossChainUnshield"
  ): TypedContractMethod<
    [
      _transaction: TransactionStruct,
      destinationDomain: BigNumberish,
      finalRecipient: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReceiveFinalizedMessage"
  ): TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReceiveUnfinalizedMessage"
  ): TypedContractMethod<
    [
      remoteDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _shieldModule: AddressLike,
      _transactModule: AddressLike,
      _merkleModule: AddressLike,
      _verifierModule: AddressLike,
      _tokenMessenger: AddressLike,
      _messageTransmitter: AddressLike,
      _usdc: AddressLike,
      _localDomain: BigNumberish,
      _owner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRemotePool"
  ): TypedContractMethod<
    [domain: BigNumberish, poolAddress: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTestingMode"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationKey"
  ): TypedContractMethod<
    [
      nullifiers: BigNumberish,
      commitments: BigNumberish,
      key: VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shield"
  ): TypedContractMethod<
    [_shieldRequests: ShieldRequestStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transact"
  ): TypedContractMethod<
    [_transactions: TransactionStruct[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RemotePoolSet"
  ): TypedContractEvent<
    RemotePoolSetEvent.InputTuple,
    RemotePoolSetEvent.OutputTuple,
    RemotePoolSetEvent.OutputObject
  >;
  getEvent(
    key: "TestingModeSet"
  ): TypedContractEvent<
    TestingModeSetEvent.InputTuple,
    TestingModeSetEvent.OutputTuple,
    TestingModeSetEvent.OutputObject
  >;

  filters: {
    "RemotePoolSet(uint32,bytes32)": TypedContractEvent<
      RemotePoolSetEvent.InputTuple,
      RemotePoolSetEvent.OutputTuple,
      RemotePoolSetEvent.OutputObject
    >;
    RemotePoolSet: TypedContractEvent<
      RemotePoolSetEvent.InputTuple,
      RemotePoolSetEvent.OutputTuple,
      RemotePoolSetEvent.OutputObject
    >;

    "TestingModeSet(bool)": TypedContractEvent<
      TestingModeSetEvent.InputTuple,
      TestingModeSetEvent.OutputTuple,
      TestingModeSetEvent.OutputObject
    >;
    TestingModeSet: TypedContractEvent<
      TestingModeSetEvent.InputTuple,
      TestingModeSetEvent.OutputTuple,
      TestingModeSetEvent.OutputObject
    >;
  };
}
