/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArmadaYieldVault } from "./ArmadaYieldVault";
export type { IAaveSpoke } from "./IAaveSpoke";
export type { IArmadaTreasury } from "./IArmadaTreasury";
