/**
 * Generate Poseidon contract bytecode using circomlibjs (npm package)
 *
 * This generates the actual Poseidon hash function bytecode that the
 * stub contracts need to be replaced with.
 *
 * The generated bytecode is committed to lib/poseidon_bytecode.json so
 * deployment works out of the box. Only re-run this script if you need
 * to regenerate the bytecode (e.g., after updating circomlibjs).
 *
 * Usage: node scripts/generate_poseidon.cjs
 */

const path = require("path");
const fs = require("fs");

// Use the npm-installed circomlibjs package
const { poseidonContract } = require("circomlibjs");

// Generate bytecode for PoseidonT3 (2 inputs) and PoseidonT4 (3 inputs)
// T = nInputs + 1, so T3 = 2 inputs, T4 = 3 inputs
const poseidonT3Bytecode = poseidonContract.createCode(2);
const poseidonT4Bytecode = poseidonContract.createCode(3);

const poseidonT3ABI = poseidonContract.generateABI(2);
const poseidonT4ABI = poseidonContract.generateABI(3);

// Output for deployment
const output = {
  PoseidonT3: {
    bytecode: poseidonT3Bytecode,
    abi: poseidonT3ABI
  },
  PoseidonT4: {
    bytecode: poseidonT4Bytecode,
    abi: poseidonT4ABI
  }
};

// Write to file
const outputPath = path.join(__dirname, "..", "lib", "poseidon_bytecode.json");
fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));

console.log("Generated Poseidon bytecode:");
console.log(`  PoseidonT3 (2 inputs): ${poseidonT3Bytecode.length} bytes`);
console.log(`  PoseidonT4 (3 inputs): ${poseidonT4Bytecode.length} bytes`);
console.log(`\nSaved to: ${outputPath}`);
