/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMerkleModule,
  IMerkleModuleInterface,
} from "../../../../contracts/privacy-pool/interfaces/IMerkleModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newCommitments",
        type: "uint256",
      },
    ],
    name: "getInsertionTreeNumberAndStartingIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "treeNum",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "startIndex",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_left",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_right",
        type: "bytes32",
      },
    ],
    name: "hashLeftRight",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "initializeMerkle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_leafHashes",
        type: "bytes32[]",
      },
    ],
    name: "insertLeaves",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMerkleModule__factory {
  static readonly abi = _abi;
  static createInterface(): IMerkleModuleInterface {
    return new Interface(_abi) as IMerkleModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMerkleModule {
    return new Contract(address, _abi, runner) as unknown as IMerkleModule;
  }
}
