/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArmadaYieldAdapter } from "./ArmadaYieldAdapter";
export type { IArmadaYieldVault } from "./IArmadaYieldVault";
