// ABOUTME: End-to-end verification of Armada circuits — shield, private transfer, and unshield
// ABOUTME: with proofs generated by Armada WASM/ZKEY and verified on-chain against Armada vkeys.

/**
 * End-to-End Verification: Armada Circuits
 *
 * Tests the full flow:
 *   1. Shield USDC into PrivacyPool (using Armada vkeys on-chain)
 *   2. Private transfer Alice → Bob (SDK generates proof with Armada WASM/ZKEY)
 *   3. Unshield USDC from PrivacyPool (different circuit shape)
 *
 * All proofs generated by Armada circuits, verified on-chain by Armada vkeys.
 *
 * Prerequisites:
 *   npm run chains    # terminal 1
 *   source config/local.env && npm run setup  # terminal 2
 *   npx hardhat run scripts/capture/e2e-armada-circuits.ts --network hub
 */

import { ethers } from 'hardhat';

import { initializeEngine, shutdownEngine, clearDatabase, getEngine } from '../../lib/sdk/init';
import { createWallet, DEFAULT_ENCRYPTION_KEY } from '../../lib/sdk/wallet';
import { initializeProver } from '../../lib/sdk/prover';
import { createShieldRequest, generateShieldPrivateKey } from '../../lib/sdk/shield';
import { loadNetworkIntoEngine, scanWalletBalances } from '../../lib/sdk/network';
import { createPrivateTransfer, createUnshield } from '../../lib/sdk/transfer';
import { getChainById, getRpcUrl } from '../../lib/sdk/chain-config';
import { loadVerificationKeys, TESTING_ARTIFACT_CONFIGS } from '../../lib/artifacts';

import { TXIDVersion, POI, POINodeInterface } from '@railgun-community/engine';

class StubPOINodeInterface extends POINodeInterface {
  isActive(): boolean { return false; }
  async isRequired(): Promise<boolean> { return false; }
  async getPOIsPerList(): Promise<Record<string, any>> { return {}; }
  async getPOIMerkleProofs(): Promise<any[]> { return []; }
  async validatePOIMerkleroots(): Promise<boolean> { return true; }
  async submitPOI(): Promise<void> { /* no-op */ }
  async submitLegacyTransactProofs(): Promise<void> { /* no-op */ }
}
POI.init([], new StubPOINodeInterface());

const deployments = require('../../deployments/privacy-pool-hub.json');

async function main() {
  console.log('='.repeat(60));
  console.log('  End-to-End: Armada Circuits Verification');
  console.log('='.repeat(60));

  const [deployer, aliceSigner, bobSigner] = await ethers.getSigners();

  // Load contracts
  const privacyPool = await ethers.getContractAt('PrivacyPool', deployments.contracts.privacyPool);
  const usdc = await ethers.getContractAt('MockUSDCV2', deployments.cctp.usdc);
  const usdcAddress = await usdc.getAddress();

  // Verify on-chain vkeys are Armada's (check a few shapes)
  console.log('\nVerifying on-chain verification keys...');
  const shapes = [[1, 1], [1, 2], [2, 2], [3, 2]];
  for (const [n, m] of shapes) {
    const vkey = await privacyPool.getVerificationKey(n, m);
    if (vkey.alpha1.x === 0n) {
      throw new Error(`VK not set for ${n}x${m}`);
    }
    console.log(`  ✓ ${n}x${m} vkey registered (alpha1.x = ${vkey.alpha1.x.toString().slice(0, 20)}...)`);
  }

  // Verify SNARK verification is enabled (not testing mode)
  const testingMode = await privacyPool.testingMode();
  console.log(`  Testing mode: ${testingMode} (should be false)`);
  if (testingMode) throw new Error('Testing mode is ON — proofs are not verified!');

  // Initialize engine
  console.log('\nInitializing engine with Armada circuits...');
  clearDatabase();
  await initializeEngine('e2e');
  const chain = getChainById(deployments.chainId)!;
  await loadNetworkIntoEngine(chain, await privacyPool.getAddress(), ethers.ZeroAddress, getRpcUrl(chain), deployments.deployBlock ?? 0);
  await initializeProver();

  // Create wallets
  const aliceWalletInfo = await createWallet(DEFAULT_ENCRYPTION_KEY);
  const bobWalletInfo = await createWallet(DEFAULT_ENCRYPTION_KEY);
  const engine = getEngine();
  const aliceWallet = engine.wallets[aliceWalletInfo.id];
  const bobWallet = engine.wallets[bobWalletInfo.id];

  console.log(`Alice: ${aliceWalletInfo.railgunAddress}`);
  console.log(`Bob:   ${bobWalletInfo.railgunAddress}`);

  // ═══════════════════════════════════════════════════════════
  // STEP 1: SHIELD (100 USDC)
  // ═══════════════════════════════════════════════════════════
  console.log('\n' + '─'.repeat(40));
  console.log('  STEP 1: SHIELD 100 USDC');
  console.log('─'.repeat(40));

  const shieldAmount = ethers.parseUnits('100', 6);
  const shieldPrivateKey = generateShieldPrivateKey();
  const { shieldRequest } = await createShieldRequest(
    { railgunAddress: aliceWalletInfo.railgunAddress, amount: shieldAmount, tokenAddress: usdcAddress },
    shieldPrivateKey,
  );

  await (await usdc.mint(await aliceSigner.getAddress(), shieldAmount)).wait();
  await (await usdc.connect(aliceSigner).approve(await privacyPool.getAddress(), shieldAmount)).wait();
  const shieldTx = await privacyPool.connect(aliceSigner).shield([shieldRequest], ethers.ZeroAddress);
  const shieldReceipt = await shieldTx.wait();
  console.log(`✓ Shield tx: ${shieldReceipt!.hash}`);

  await scanWalletBalances(aliceWalletInfo.id, chain);
  await new Promise(r => setTimeout(r, 2000));

  const aliceTxos = await aliceWallet.TXOs(TXIDVersion.V2_PoseidonMerkle, chain);
  console.log(`✓ Alice has ${aliceTxos.length} UTXO(s), value=${ethers.formatUnits(aliceTxos[0].note.value, 6)} USDC`);

  // ═══════════════════════════════════════════════════════════
  // STEP 2: PRIVATE TRANSFER (Alice → Bob, 30 USDC)
  // ═══════════════════════════════════════════════════════════
  console.log('\n' + '─'.repeat(40));
  console.log('  STEP 2: PRIVATE TRANSFER 30 USDC');
  console.log('─'.repeat(40));

  const transferAmount = ethers.parseUnits('30', 6);
  const transferResult = await createPrivateTransfer({
    wallet: aliceWallet,
    chain,
    tokenAddress: usdcAddress,
    recipientAddress: bobWalletInfo.railgunAddress,
    amount: transferAmount,
    encryptionKey: DEFAULT_ENCRYPTION_KEY,
    progressCallback: (p: any) => process.stdout.write('.'),
  });
  console.log('');

  const transferTx = await aliceSigner.sendTransaction({
    to: transferResult.contractTransaction.to,
    data: transferResult.contractTransaction.data,
  });
  const transferReceipt = await transferTx.wait();
  console.log(`✓ Transfer tx: ${transferReceipt!.hash}`);

  const provedTx = transferResult.transactions[0];
  console.log(`✓ Circuit shape: ${provedTx.nullifiers.length}x${provedTx.commitments.length}`);
  console.log(`✓ Proof verified on-chain (tx succeeded = Groth16 pairing check passed)`);

  // Verify Bob received
  await scanWalletBalances(bobWalletInfo.id, chain);
  await new Promise(r => setTimeout(r, 2000));
  const bobTxos = await bobWallet.TXOs(TXIDVersion.V2_PoseidonMerkle, chain);
  console.log(`✓ Bob has ${bobTxos.length} UTXO(s), value=${ethers.formatUnits(bobTxos[0].note.value, 6)} USDC`);

  // ═══════════════════════════════════════════════════════════
  // STEP 3: UNSHIELD (Bob → public address, 10 USDC)
  // ═══════════════════════════════════════════════════════════
  console.log('\n' + '─'.repeat(40));
  console.log('  STEP 3: UNSHIELD 10 USDC');
  console.log('─'.repeat(40));

  const unshieldAmount = ethers.parseUnits('10', 6);
  const bobPublicAddress = await bobSigner.getAddress();

  const unshieldResult = await createUnshield({
    wallet: bobWallet,
    chain,
    tokenAddress: usdcAddress,
    recipientAddress: bobPublicAddress,
    amount: unshieldAmount,
    encryptionKey: DEFAULT_ENCRYPTION_KEY,
    progressCallback: (p: any) => process.stdout.write('.'),
  });
  console.log('');

  const unshieldTx = await bobSigner.sendTransaction({
    to: unshieldResult.contractTransaction.to,
    data: unshieldResult.contractTransaction.data,
  });
  const unshieldReceipt = await unshieldTx.wait();
  console.log(`✓ Unshield tx: ${unshieldReceipt!.hash}`);

  const unshieldProvedTx = unshieldResult.transactions[0];
  console.log(`✓ Circuit shape: ${unshieldProvedTx.nullifiers.length}x${unshieldProvedTx.commitments.length}`);
  console.log(`✓ Proof verified on-chain (tx succeeded = Groth16 pairing check passed)`);

  // Verify Bob's public balance increased
  const bobPublicBalance = await usdc.balanceOf(bobPublicAddress);
  console.log(`✓ Bob public USDC balance: ${ethers.formatUnits(bobPublicBalance, 6)}`);

  // ═══════════════════════════════════════════════════════════
  // SUMMARY
  // ═══════════════════════════════════════════════════════════
  console.log('\n' + '='.repeat(60));
  console.log('  END-TO-END VERIFICATION PASSED');
  console.log('='.repeat(60));
  console.log('  ✓ Shield:   100 USDC shielded (Armada vkeys on-chain)');
  console.log(`  ✓ Transfer: 30 USDC sent (1x2 circuit, proof generated by Armada WASM/ZKEY)`);
  console.log(`  ✓ Unshield: 10 USDC withdrawn (proof generated by Armada WASM/ZKEY)`);
  console.log('  ✓ All proofs verified on-chain via Groth16 pairing checks');
  console.log('  ✓ No railgun-circuit-test-artifacts dependency');

  await shutdownEngine();
}

main().then(() => {
  // Ethers JsonRpcProviders keep polling for blocks, holding the event loop
  // open after the engine unloads; exit explicitly once work is done.
  process.exit(0);
}).catch(async (err) => {
  console.error('\n❌ E2E test failed:', err);
  try { await shutdownEngine(); } catch { /* ignore */ }
  process.exit(1);
});
